In [1]:
# =============================================================================
# 10_EXPORT_FOR_POWERBI.IPYNB - COPY/PASTE NOTEBOOK CELLS
# Banking Stress Testing Framework - Python V2 Migration
#
# SAS V1 EQUIVALENCE
# Input datasets:
#   STRESS.ECL_SUMMARY
#   STRESS.PRODUCT_ECL_SUMMARY
#   STRESS.SEGMENT_ECL_SUMMARY
#
# Python V2 source files from Module 09:
#   validation/09_ecl_summary.csv
#   validation/09_product_ecl_summary.csv
#   validation/09_segment_ecl_summary.csv
#
# Power BI output files:
#   PowerBI/ecl_summary.csv
#   PowerBI/product_ecl_summary.csv
#   PowerBI/segment_ecl_summary.csv
#
# RUNTIME STANDARD
# Google Drive mount point : /content/gdrive
# Project root             : /content/gdrive/MyDrive/
#                            Banking_Stress_Testing_V2_Python
#
# INSTRUCTIONS
# 1. Create 10_Export_For_PowerBI.ipynb in Google Colab.
# 2. Create 8 separate Code cells.
# 3. Copy each CELL section below into the corresponding notebook cell.
# 4. Run CELL 01 through CELL 08 strictly in sequence.
# 5. Continue only when each block ends with BLOCK STATUS : SUCCESS.
# =============================================================================


# =============================================================================
# CELL 01 - MODULE HEADER
# =============================================================================

from datetime import datetime

module_start_timestamp = datetime.now()

print("=" * 80)
print("BANKING STRESS TESTING FRAMEWORK")
print("PYTHON V2 MIGRATION")
print("MODULE : 10_EXPORT_FOR_POWERBI")
print(
    "EXECUTION STARTED :",
    module_start_timestamp.strftime("%Y-%m-%d %H:%M:%S")
)
print("=" * 80)

================================================================================
BANKING STRESS TESTING FRAMEWORK
PYTHON V2 MIGRATION
MODULE : 10_EXPORT_FOR_POWERBI
EXECUTION STARTED : 2026-10-14 03:31:41
================================================================================

In [2]:
# =============================================================================
# CELL 02 - BLOCK 1: ENVIRONMENT, GDRIVE MOUNT, PATHS, AND LOGGING
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = 0
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 1 : ENVIRONMENT, GDRIVE MOUNT, PATHS, AND LOGGING")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    from google.colab import drive
    from pathlib import Path
    import hashlib
    import logging
    import sys
    import numpy as np
    import pandas as pd

    MOUNT_POINT = Path("/content/gdrive")

    if not (MOUNT_POINT / "MyDrive").exists():
        if MOUNT_POINT.exists() and not any(MOUNT_POINT.iterdir()):
            MOUNT_POINT.rmdir()
        drive.mount(str(MOUNT_POINT))
    else:
        print("Google Drive is already mounted at:", MOUNT_POINT)

    PROJECT_ROOT = (
        MOUNT_POINT
        / "MyDrive"
        / "Banking_Stress_Testing_V2_Python"
    )

    VALIDATION_DIR = PROJECT_ROOT / "validation"
    POWERBI_DIR = PROJECT_ROOT / "PowerBI"
    LOG_DIR = PROJECT_ROOT / "logs"

    ECL_SOURCE_FILE = VALIDATION_DIR / "09_ecl_summary.csv"
    PRODUCT_SOURCE_FILE = VALIDATION_DIR / "09_product_ecl_summary.csv"
    SEGMENT_SOURCE_FILE = VALIDATION_DIR / "09_segment_ecl_summary.csv"

    ECL_EXPORT_FILE = POWERBI_DIR / "ecl_summary.csv"
    PRODUCT_EXPORT_FILE = POWERBI_DIR / "product_ecl_summary.csv"
    SEGMENT_EXPORT_FILE = POWERBI_DIR / "segment_ecl_summary.csv"

    EXPORT_VALIDATION_FILE = (
        VALIDATION_DIR / "10_powerbi_export_validation.csv"
    )
    EXPORT_MANIFEST_FILE = (
        VALIDATION_DIR / "10_powerbi_export_manifest.csv"
    )
    EXPORT_SAMPLE_FILE = (
        VALIDATION_DIR / "10_powerbi_export_sample.csv"
    )
    LOG_FILE = LOG_DIR / "10_Export_For_PowerBI.log"

    POWERBI_DIR.mkdir(parents=True, exist_ok=True)
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    logger = logging.getLogger("10_Export_For_PowerBI")
    logger.setLevel(logging.INFO)
    if logger.hasHandlers():
        logger.handlers.clear()

    log_formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s"
    )
    file_handler = logging.FileHandler(
        LOG_FILE,
        mode="w",
        encoding="utf-8"
    )
    file_handler.setFormatter(log_formatter)
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(log_formatter)
    logger.addHandler(file_handler)
    logger.addHandler(console_handler)

    if not PROJECT_ROOT.exists():
        raise FileNotFoundError(
            f"Project root was not found: {PROJECT_ROOT}"
        )

    source_files = [
        ECL_SOURCE_FILE,
        PRODUCT_SOURCE_FILE,
        SEGMENT_SOURCE_FILE,
    ]
    missing_source_files = [
        str(file_path)
        for file_path in source_files
        if not file_path.exists()
    ]

    if missing_source_files:
        raise FileNotFoundError(
            "Module 09 reporting inputs were not found: "
            f"{missing_source_files}"
        )

    print("Drive Mount Exists:", MOUNT_POINT.exists())
    print("Project Root Exists:", PROJECT_ROOT.exists())
    print("Validation Directory Exists:", VALIDATION_DIR.exists())
    print("Power BI Directory:", POWERBI_DIR)
    print("Power BI Directory Exists:", POWERBI_DIR.exists())
    print("Executive Summary Exists:", ECL_SOURCE_FILE.exists())
    print("Product Summary Exists:", PRODUCT_SOURCE_FILE.exists())
    print("Segment Summary Exists:", SEGMENT_SOURCE_FILE.exists())
    print("Execution Log:", LOG_FILE)

    logger.info(
        "Environment, gdrive mount, paths, and logging configured successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    if "logger" in locals():
        logger.exception(
            "Block 1 failed during environment configuration."
        )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 1 : ENVIRONMENT, GDRIVE MOUNT, PATHS, AND LOGGING
START TIME : 2026-10-14 03:35:52
================================================================================
Mounted at /content/gdrive
Drive Mount Exists: True
Project Root Exists: True
Validation Directory Exists: True
Power BI Directory: /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI
Power BI Directory Exists: True
Executive Summary Exists: True
Product Summary Exists: True
Segment Summary Exists: True
Execution Log: /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/logs/10_Export_For_PowerBI.log
2026-10-14 03:36:27,664 | INFO | Environment, gdrive mount, paths, and logging configured successfully.

INFO:10_Export_For_PowerBI:Environment, gdrive mount, paths, and logging configured successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 0
OUTPUT RECORDS     : 0
RECORDS PROCESSED  : 0
END TIME           : 2026-10-14 03:36:27
DURATION (SECONDS) : 35.606
================================================================================

In [3]:
# =============================================================================
# CELL 03 - BLOCK 2: LOAD AND VALIDATE MODULE 09 REPORTING DATASETS
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = 0
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 2 : LOAD AND VALIDATE MODULE 09 REPORTING DATASETS")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    ecl_summary = pd.read_csv(
        ECL_SOURCE_FILE,
        low_memory=False
    )
    product_ecl_summary = pd.read_csv(
        PRODUCT_SOURCE_FILE,
        low_memory=False
    )
    segment_ecl_summary = pd.read_csv(
        SEGMENT_SOURCE_FILE,
        low_memory=False
    )

    ecl_required_columns = [
        "Scenario_Name",
        "Account_Count",
        "Total_Exposure",
        "Total_Base_ECL",
        "Total_Stressed_ECL",
        "Incremental_Stress_Loss",
    ]
    product_required_columns = [
        "Scenario_Name",
        "Product_Type",
        "Account_Count",
        "Total_Exposure",
        "Total_Stressed_ECL",
    ]
    segment_required_columns = [
        "Scenario_Name",
        "Risk_Segment",
        "Account_Count",
        "Total_Exposure",
        "Total_Stressed_ECL",
    ]

    missing_ecl_columns = sorted(
        set(ecl_required_columns) - set(ecl_summary.columns)
    )
    missing_product_columns = sorted(
        set(product_required_columns) - set(product_ecl_summary.columns)
    )
    missing_segment_columns = sorted(
        set(segment_required_columns) - set(segment_ecl_summary.columns)
    )

    if missing_ecl_columns:
        raise ValueError(
            f"Executive summary columns are missing: {missing_ecl_columns}"
        )
    if missing_product_columns:
        raise ValueError(
            f"Product summary columns are missing: {missing_product_columns}"
        )
    if missing_segment_columns:
        raise ValueError(
            f"Segment summary columns are missing: {missing_segment_columns}"
        )

    ecl_missing_values = int(
        ecl_summary[ecl_required_columns].isna().sum().sum()
    )
    product_missing_values = int(
        product_ecl_summary[product_required_columns].isna().sum().sum()
    )
    segment_missing_values = int(
        segment_ecl_summary[segment_required_columns].isna().sum().sum()
    )

    ecl_duplicate_keys = int(
        ecl_summary[["Scenario_Name"]].duplicated().sum()
    )
    product_duplicate_keys = int(
        product_ecl_summary[
            ["Scenario_Name", "Product_Type"]
        ].duplicated().sum()
    )
    segment_duplicate_keys = int(
        segment_ecl_summary[
            ["Scenario_Name", "Risk_Segment"]
        ].duplicated().sum()
    )

    expected_scenarios = {
        "Baseline",
        "Mild_Stress",
        "Severe_Stress",
    }
    ecl_scenarios = set(ecl_summary["Scenario_Name"].unique())
    product_scenarios = set(product_ecl_summary["Scenario_Name"].unique())
    segment_scenarios = set(segment_ecl_summary["Scenario_Name"].unique())

    ecl_account_total = int(ecl_summary["Account_Count"].sum())
    product_account_total = int(
        product_ecl_summary["Account_Count"].sum()
    )
    segment_account_total = int(
        segment_ecl_summary["Account_Count"].sum()
    )

    if len(ecl_summary) != 3:
        raise ValueError(
            "Executive summary does not contain three scenario rows."
        )
    if ecl_missing_values + product_missing_values + segment_missing_values > 0:
        raise ValueError(
            "Missing values were found in required Power BI fields."
        )
    if ecl_duplicate_keys + product_duplicate_keys + segment_duplicate_keys > 0:
        raise ValueError(
            "Duplicate reporting keys were found."
        )
    if not (
        ecl_scenarios
        == product_scenarios
        == segment_scenarios
        == expected_scenarios
    ):
        raise ValueError(
            "Scenario values are inconsistent across reporting datasets."
        )
    if not (
        ecl_account_total
        == product_account_total
        == segment_account_total
        == 30000
    ):
        raise ValueError(
            "Account totals do not reconcile across reporting datasets."
        )

    input_record_count = (
        len(ecl_summary)
        + len(product_ecl_summary)
        + len(segment_ecl_summary)
    )
    records_processed = input_record_count

    print("=" * 80)
    print("MODULE 09 REPORTING DATASETS LOADED SUCCESSFULLY")
    print("=" * 80)
    print("Executive Summary Rows:", len(ecl_summary))
    print("Product Summary Rows:", len(product_ecl_summary))
    print("Segment Summary Rows:", len(segment_ecl_summary))
    print("Combined Input Rows:", input_record_count)
    print("Executive Account Total:", ecl_account_total)
    print("Product Account Total:", product_account_total)
    print("Segment Account Total:", segment_account_total)
    print("Executive Missing Values:", ecl_missing_values)
    print("Product Missing Values:", product_missing_values)
    print("Segment Missing Values:", segment_missing_values)
    print("Executive Duplicate Keys:", ecl_duplicate_keys)
    print("Product Duplicate Keys:", product_duplicate_keys)
    print("Segment Duplicate Keys:", segment_duplicate_keys)
    print("Input Validation Status: PASS")

    print("\nExecutive Summary:")
    display(ecl_summary.round(2))

    logger.info(
        "Module 09 reporting datasets loaded and validated successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception(
        "Block 2 failed while loading Module 09 reporting datasets."
    )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 2 : LOAD AND VALIDATE MODULE 09 REPORTING DATASETS
START TIME : 2026-10-14 03:39:38
================================================================================
================================================================================
MODULE 09 REPORTING DATASETS LOADED SUCCESSFULLY
================================================================================
Executive Summary Rows: 3
Product Summary Rows: 18
Segment Summary Rows: 9
Combined Input Rows: 30
Executive Account Total: 30000
Product Account Total: 30000
Segment Account Total: 30000
Executive Missing Values: 0
Product Missing Values: 0
Segment Missing Values: 0
Executive Duplicate Keys: 0
Product Duplicate Keys: 0
Segment Duplicate Keys: 0
Input Validation Status: PASS

Executive Summary:

,Scenario_Name,Account_Count,Total_Exposure,Total_Base_ECL,Total_Stressed_ECL,Incremental_Stress_Loss
0,Baseline,10000,4.758191e+10,9.299713e+08,9.299713e+08,0.000000e+00
1,Mild_Stress,10000,4.758191e+10,9.299713e+08,1.278711e+09,3.487392e+08
2,Severe_Stress,10000,4.758191e+10,9.299713e+08,2.031954e+09,1.101983e+09

2026-10-14 03:39:38,983 | INFO | Module 09 reporting datasets loaded and validated successfully.

INFO:10_Export_For_PowerBI:Module 09 reporting datasets loaded and validated successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30
OUTPUT RECORDS     : 0
RECORDS PROCESSED  : 30
END TIME           : 2026-10-14 03:39:38
DURATION (SECONDS) : 0.985
================================================================================

In [4]:
# =============================================================================
# CELL 04 - BLOCK 3: PREPARE POWER BI EXPORT DATASETS
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = (
    len(ecl_summary)
    + len(product_ecl_summary)
    + len(segment_ecl_summary)
)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 3 : PREPARE POWER BI EXPORT DATASETS")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    # Preserve the exact SAS V1 reporting structures and column names.
    powerbi_ecl_summary = ecl_summary[
        ecl_required_columns
    ].copy(deep=True)

    powerbi_product_summary = product_ecl_summary[
        product_required_columns
    ].copy(deep=True)

    powerbi_segment_summary = segment_ecl_summary[
        segment_required_columns
    ].copy(deep=True)

    # Apply stable business ordering for consistent Power BI refreshes.
    scenario_order = {
        "Baseline": 1,
        "Mild_Stress": 2,
        "Severe_Stress": 3,
    }

    powerbi_ecl_summary["_Scenario_Order"] = (
        powerbi_ecl_summary["Scenario_Name"].map(scenario_order)
    )
    powerbi_ecl_summary = (
        powerbi_ecl_summary
        .sort_values("_Scenario_Order", kind="stable")
        .drop(columns="_Scenario_Order")
        .reset_index(drop=True)
    )

    powerbi_product_summary["_Scenario_Order"] = (
        powerbi_product_summary["Scenario_Name"].map(scenario_order)
    )
    powerbi_product_summary = (
        powerbi_product_summary
        .sort_values(
            ["_Scenario_Order", "Product_Type"],
            kind="stable"
        )
        .drop(columns="_Scenario_Order")
        .reset_index(drop=True)
    )

    powerbi_segment_summary["_Scenario_Order"] = (
        powerbi_segment_summary["Scenario_Name"].map(scenario_order)
    )
    powerbi_segment_summary = (
        powerbi_segment_summary
        .sort_values(
            ["_Scenario_Order", "Risk_Segment"],
            kind="stable"
        )
        .drop(columns="_Scenario_Order")
        .reset_index(drop=True)
    )

    prepared_missing_values = int(
        powerbi_ecl_summary.isna().sum().sum()
        + powerbi_product_summary.isna().sum().sum()
        + powerbi_segment_summary.isna().sum().sum()
    )

    structure_exceptions = 0
    structure_exceptions += int(
        list(powerbi_ecl_summary.columns) != ecl_required_columns
    )
    structure_exceptions += int(
        list(powerbi_product_summary.columns)
        != product_required_columns
    )
    structure_exceptions += int(
        list(powerbi_segment_summary.columns)
        != segment_required_columns
    )
    structure_exceptions += int(
        len(powerbi_ecl_summary) != len(ecl_summary)
    )
    structure_exceptions += int(
        len(powerbi_product_summary) != len(product_ecl_summary)
    )
    structure_exceptions += int(
        len(powerbi_segment_summary) != len(segment_ecl_summary)
    )

    if prepared_missing_values > 0:
        raise ValueError(
            "Prepared Power BI datasets contain missing values."
        )
    if structure_exceptions > 0:
        raise ValueError(
            "Prepared Power BI dataset structure validation failed."
        )

    output_record_count = (
        len(powerbi_ecl_summary)
        + len(powerbi_product_summary)
        + len(powerbi_segment_summary)
    )
    records_processed = input_record_count

    print("=" * 80)
    print("POWER BI DATASETS PREPARED")
    print("=" * 80)
    print("Executive Export Rows:", len(powerbi_ecl_summary))
    print("Product Export Rows:", len(powerbi_product_summary))
    print("Segment Export Rows:", len(powerbi_segment_summary))
    print("Combined Export Rows:", output_record_count)
    print("Prepared Missing Values:", prepared_missing_values)
    print("Structure Exceptions:", structure_exceptions)
    print("Power BI Preparation Status: PASS")

    print("\nProduct Summary Sample:")
    display(powerbi_product_summary.head(12).round(2))

    print("\nSegment Summary Sample:")
    display(powerbi_segment_summary.head(9).round(2))

    logger.info(
        "Power BI export datasets prepared successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception(
        "Block 3 failed while preparing Power BI datasets."
    )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 3 : PREPARE POWER BI EXPORT DATASETS
START TIME : 2026-10-14 03:41:22
================================================================================
================================================================================
POWER BI DATASETS PREPARED
================================================================================
Executive Export Rows: 3
Product Export Rows: 18
Segment Export Rows: 9
Combined Export Rows: 30
Prepared Missing Values: 0
Structure Exceptions: 0
Power BI Preparation Status: PASS

Product Summary Sample:

,Scenario_Name,Product_Type,Account_Count,Total_Exposure,Total_Stressed_ECL
0,Baseline,Auto Loan,2088,3.782912e+09,7.183463e+07
1,Baseline,Corporate Loan,405,1.581266e+10,3.841704e+08
2,Baseline,Credit Card,1555,3.931793e+08,1.832473e+07
3,Baseline,Mortgage,2550,1.594025e+10,1.736888e+08
4,Baseline,Personal Loan,2117,2.170796e+09,7.134425e+07
5,Baseline,SME Loan,1285,9.482109e+09,2.106084e+08
6,Mild_Stress,Auto Loan,2088,3.782912e+09,9.877262e+07
7,Mild_Stress,Corporate Loan,405,1.581266e+10,5.282344e+08
8,Mild_Stress,Credit Card,1555,3.931793e+08,2.519651e+07
9,Mild_Stress,Mortgage,2550,1.594025e+10,2.388221e+08
10,Mild_Stress,Personal Loan,2117,2.170796e+09,9.809835e+07
11,Mild_Stress,SME Loan,1285,9.482109e+09,2.895866e+08

Segment Summary Sample:

,Scenario_Name,Risk_Segment,Account_Count,Total_Exposure,Total_Stressed_ECL
0,Baseline,High Risk,2485,1.172251e+10,4.214570e+08
1,Baseline,Low Risk,2535,1.236121e+10,8.908115e+07
2,Baseline,Medium Risk,4980,2.349819e+10,4.194331e+08
3,Mild_Stress,High Risk,2485,1.172251e+10,5.795034e+08
4,Mild_Stress,Low Risk,2535,1.236121e+10,1.224866e+08
5,Mild_Stress,Medium Risk,4980,2.349819e+10,5.767205e+08
6,Severe_Stress,High Risk,2485,1.172251e+10,9.208785e+08
7,Severe_Stress,Low Risk,2535,1.236121e+10,1.946506e+08
8,Severe_Stress,Medium Risk,4980,2.349819e+10,9.164251e+08

2026-10-14 03:41:23,052 | INFO | Power BI export datasets prepared successfully.

INFO:10_Export_For_PowerBI:Power BI export datasets prepared successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30
OUTPUT RECORDS     : 30
RECORDS PROCESSED  : 30
END TIME           : 2026-10-14 03:41:23
DURATION (SECONDS) : 0.075
================================================================================

In [5]:

# =============================================================================
# CELL 05 - BLOCK 4: EXPORT CSV FILES FOR POWER BI
# SAS V1: PROC EXPORT DBMS=CSV REPLACE
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = output_record_count
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 4 : EXPORT CSV FILES FOR POWER BI")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    powerbi_ecl_summary.to_csv(
        ECL_EXPORT_FILE,
        index=False,
        encoding="utf-8"
    )
    powerbi_product_summary.to_csv(
        PRODUCT_EXPORT_FILE,
        index=False,
        encoding="utf-8"
    )
    powerbi_segment_summary.to_csv(
        SEGMENT_EXPORT_FILE,
        index=False,
        encoding="utf-8"
    )

    exported_files = [
        ECL_EXPORT_FILE,
        PRODUCT_EXPORT_FILE,
        SEGMENT_EXPORT_FILE,
    ]

    output_record_count = len(exported_files)
    records_processed = input_record_count

    print("=" * 80)
    print("POWER BI CSV EXPORT COMPLETED")
    print("=" * 80)
    print("1.", ECL_EXPORT_FILE)
    print("2.", PRODUCT_EXPORT_FILE)
    print("3.", SEGMENT_EXPORT_FILE)
    print("Exported File Count:", output_record_count)

    logger.info(
        "Three Power BI CSV files exported successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception(
        "Block 4 failed while exporting Power BI CSV files."
    )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT FILES       :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 4 : EXPORT CSV FILES FOR POWER BI
START TIME : 2026-10-14 03:42:39
================================================================================
================================================================================
POWER BI CSV EXPORT COMPLETED
================================================================================
1. /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI/ecl_summary.csv
2. /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI/product_ecl_summary.csv
3. /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI/segment_ecl_summary.csv
Exported File Count: 3
2026-10-14 03:42:40,113 | INFO | Three Power BI CSV files exported successfully.

INFO:10_Export_For_PowerBI:Three Power BI CSV files exported successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30
OUTPUT FILES       : 3
RECORDS PROCESSED  : 30
END TIME           : 2026-10-14 03:42:40
DURATION (SECONDS) : 0.189
================================================================================

In [6]:

# =============================================================================
# CELL 05 - BLOCK 4: EXPORT CSV FILES FOR POWER BI
# SAS V1: PROC EXPORT DBMS=CSV REPLACE
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = output_record_count
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 4 : EXPORT CSV FILES FOR POWER BI")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    powerbi_ecl_summary.to_csv(
        ECL_EXPORT_FILE,
        index=False,
        encoding="utf-8"
    )
    powerbi_product_summary.to_csv(
        PRODUCT_EXPORT_FILE,
        index=False,
        encoding="utf-8"
    )
    powerbi_segment_summary.to_csv(
        SEGMENT_EXPORT_FILE,
        index=False,
        encoding="utf-8"
    )

    exported_files = [
        ECL_EXPORT_FILE,
        PRODUCT_EXPORT_FILE,
        SEGMENT_EXPORT_FILE,
    ]

    output_record_count = len(exported_files)
    records_processed = input_record_count

    print("=" * 80)
    print("POWER BI CSV EXPORT COMPLETED")
    print("=" * 80)
    print("1.", ECL_EXPORT_FILE)
    print("2.", PRODUCT_EXPORT_FILE)
    print("3.", SEGMENT_EXPORT_FILE)
    print("Exported File Count:", output_record_count)

    logger.info(
        "Three Power BI CSV files exported successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception(
        "Block 4 failed while exporting Power BI CSV files."
    )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT FILES       :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)


# =============================================================================
# CELL 06 - BLOCK 5: VERIFY EXPORTED FILES AND DATA CONTENT
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(exported_files)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 5 : VERIFY EXPORTED FILES AND DATA CONTENT")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    saved_ecl_summary = pd.read_csv(
        ECL_EXPORT_FILE,
        low_memory=False
    )
    saved_product_summary = pd.read_csv(
        PRODUCT_EXPORT_FILE,
        low_memory=False
    )
    saved_segment_summary = pd.read_csv(
        SEGMENT_EXPORT_FILE,
        low_memory=False
    )

    def sha256_file(file_path):
        digest = hashlib.sha256()
        with open(file_path, "rb") as file_handle:
            for chunk in iter(lambda: file_handle.read(65536), b""):
                digest.update(chunk)
        return digest.hexdigest()

    export_verification = pd.DataFrame({
        "Dataset_Name": [
            "Executive ECL Summary",
            "Product ECL Summary",
            "Segment ECL Summary",
        ],
        "File_Name": [
            ECL_EXPORT_FILE.name,
            PRODUCT_EXPORT_FILE.name,
            SEGMENT_EXPORT_FILE.name,
        ],
        "Exists": [
            ECL_EXPORT_FILE.exists(),
            PRODUCT_EXPORT_FILE.exists(),
            SEGMENT_EXPORT_FILE.exists(),
        ],
        "Size_Bytes": [
            ECL_EXPORT_FILE.stat().st_size,
            PRODUCT_EXPORT_FILE.stat().st_size,
            SEGMENT_EXPORT_FILE.stat().st_size,
        ],
        "Expected_Rows": [
            len(powerbi_ecl_summary),
            len(powerbi_product_summary),
            len(powerbi_segment_summary),
        ],
        "Saved_Rows": [
            len(saved_ecl_summary),
            len(saved_product_summary),
            len(saved_segment_summary),
        ],
        "Expected_Columns": [
            len(powerbi_ecl_summary.columns),
            len(powerbi_product_summary.columns),
            len(powerbi_segment_summary.columns),
        ],
        "Saved_Columns": [
            len(saved_ecl_summary.columns),
            len(saved_product_summary.columns),
            len(saved_segment_summary.columns),
        ],
        "SHA256": [
            sha256_file(ECL_EXPORT_FILE),
            sha256_file(PRODUCT_EXPORT_FILE),
            sha256_file(SEGMENT_EXPORT_FILE),
        ],
        "Full_Path": [
            str(ECL_EXPORT_FILE),
            str(PRODUCT_EXPORT_FILE),
            str(SEGMENT_EXPORT_FILE),
        ],
    })

    export_verification["Status"] = np.where(
        export_verification["Exists"]
        & (export_verification["Size_Bytes"] > 0)
        & (
            export_verification["Expected_Rows"]
            == export_verification["Saved_Rows"]
        )
        & (
            export_verification["Expected_Columns"]
            == export_verification["Saved_Columns"]
        ),
        "PASS",
        "FAIL"
    )

    numerical_reconciliation_exceptions = 0
    numerical_reconciliation_exceptions += int(
        not np.allclose(
            saved_ecl_summary[
                [
                    "Account_Count",
                    "Total_Exposure",
                    "Total_Base_ECL",
                    "Total_Stressed_ECL",
                    "Incremental_Stress_Loss",
                ]
            ].to_numpy(dtype="float64"),
            powerbi_ecl_summary[
                [
                    "Account_Count",
                    "Total_Exposure",
                    "Total_Base_ECL",
                    "Total_Stressed_ECL",
                    "Incremental_Stress_Loss",
                ]
            ].to_numpy(dtype="float64")
        )
    )
    numerical_reconciliation_exceptions += int(
        not np.allclose(
            saved_product_summary[
                [
                    "Account_Count",
                    "Total_Exposure",
                    "Total_Stressed_ECL",
                ]
            ].to_numpy(dtype="float64"),
            powerbi_product_summary[
                [
                    "Account_Count",
                    "Total_Exposure",
                    "Total_Stressed_ECL",
                ]
            ].to_numpy(dtype="float64")
        )
    )
    numerical_reconciliation_exceptions += int(
        not np.allclose(
            saved_segment_summary[
                [
                    "Account_Count",
                    "Total_Exposure",
                    "Total_Stressed_ECL",
                ]
            ].to_numpy(dtype="float64"),
            powerbi_segment_summary[
                [
                    "Account_Count",
                    "Total_Exposure",
                    "Total_Stressed_ECL",
                ]
            ].to_numpy(dtype="float64")
        )
    )

    if not (export_verification["Status"] == "PASS").all():
        raise ValueError(
            "One or more Power BI export files failed verification."
        )
    if numerical_reconciliation_exceptions > 0:
        raise ValueError(
            "Exported numeric values do not reconcile to source datasets."
        )

    output_record_count = len(export_verification)
    records_processed = sum(
        export_verification["Saved_Rows"]
    )

    print("=" * 80)
    print("POWER BI EXPORT VERIFICATION")
    print("=" * 80)
    display(export_verification)
    print(
        "Numerical Reconciliation Exceptions:",
        numerical_reconciliation_exceptions
    )
    print("Power BI Export Verification Status: PASS")

    logger.info(
        "Power BI exported files verified successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception(
        "Block 5 failed during exported-file verification."
    )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT FILES        :", input_record_count)
    print("VERIFIED FILES     :", output_record_count)
    print("RECORDS VERIFIED   :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 4 : EXPORT CSV FILES FOR POWER BI
START TIME : 2026-10-14 03:43:57
================================================================================
================================================================================
POWER BI CSV EXPORT COMPLETED
================================================================================
1. /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI/ecl_summary.csv
2. /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI/product_ecl_summary.csv
3. /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI/segment_ecl_summary.csv
Exported File Count: 3
2026-10-14 03:43:57,879 | INFO | Three Power BI CSV files exported successfully.

INFO:10_Export_For_PowerBI:Three Power BI CSV files exported successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 3
OUTPUT FILES       : 3
RECORDS PROCESSED  : 3
END TIME           : 2026-10-14 03:43:57
DURATION (SECONDS) : 0.029
================================================================================
================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 5 : VERIFY EXPORTED FILES AND DATA CONTENT
START TIME : 2026-10-14 03:43:57
================================================================================
================================================================================
POWER BI EXPORT VERIFICATION
================================================================================

,Dataset_Name,File_Name,Exists,Size_Bytes,Expected_Rows,Saved_Rows,Expected_Columns,Saved_Columns,SHA256,Full_Path,Status
0,Executive ECL Summary,ecl_summary.csv,True,342,3,3,6,6,8f61a218840a7a1cc84918d348c586b9ae25d13a680b58...,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
1,Product ECL Summary,product_ecl_summary.csv,True,1140,18,18,5,5,045e948be2b2696922467e40330c6ce51418dfd41ebe2f...,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
2,Segment ECL Summary,segment_ecl_summary.csv,True,603,9,9,5,5,164460eee5107d353d01a144f2c188c76484e0b4de8fb8...,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS

Numerical Reconciliation Exceptions: 0
Power BI Export Verification Status: PASS
2026-10-14 03:43:57,965 | INFO | Power BI exported files verified successfully.

INFO:10_Export_For_PowerBI:Power BI exported files verified successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT FILES        : 3
VERIFIED FILES     : 3
RECORDS VERIFIED   : 30
END TIME           : 2026-10-14 03:43:57
DURATION (SECONDS) : 0.087
================================================================================

In [7]:
# =============================================================================
# CELL 07 - BLOCK 6: CREATE VALIDATION EVIDENCE AND EXPORT MANIFEST
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(export_verification)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 6 : CREATE VALIDATION EVIDENCE AND EXPORT MANIFEST")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    validation_results = pd.DataFrame({
        "Validation_Check": [
            "Executive Source File Exists",
            "Product Source File Exists",
            "Segment Source File Exists",
            "Executive Summary Row Count",
            "Executive Summary Account Total",
            "Product Summary Account Total",
            "Segment Summary Account Total",
            "Executive Missing Required Values",
            "Product Missing Required Values",
            "Segment Missing Required Values",
            "Executive Duplicate Keys",
            "Product Duplicate Keys",
            "Segment Duplicate Keys",
            "Expected Export File Count",
            "Verified Export File Count",
            "Failed Export File Count",
            "Numerical Reconciliation Exceptions",
        ],
        "Expected_Result": [
            True,
            True,
            True,
            3,
            30000,
            30000,
            30000,
            0,
            0,
            0,
            0,
            0,
            0,
            3,
            3,
            0,
            0,
        ],
        "Actual_Result": [
            ECL_SOURCE_FILE.exists(),
            PRODUCT_SOURCE_FILE.exists(),
            SEGMENT_SOURCE_FILE.exists(),
            len(ecl_summary),
            ecl_account_total,
            product_account_total,
            segment_account_total,
            ecl_missing_values,
            product_missing_values,
            segment_missing_values,
            ecl_duplicate_keys,
            product_duplicate_keys,
            segment_duplicate_keys,
            len(exported_files),
            int((export_verification["Status"] == "PASS").sum()),
            int((export_verification["Status"] != "PASS").sum()),
            numerical_reconciliation_exceptions,
        ],
    })

    validation_results["Status"] = np.where(
        validation_results["Expected_Result"].astype(str)
        == validation_results["Actual_Result"].astype(str),
        "PASS",
        "FAIL"
    )

    failed_validations = validation_results.loc[
        validation_results["Status"] != "PASS"
    ]
    if not failed_validations.empty:
        raise ValueError(
            "One or more Module 10 validation checks failed."
        )

    export_manifest = export_verification.copy(deep=True)
    export_manifest["Export_Timestamp"] = datetime.now().strftime(
        "%Y-%m-%d %H:%M:%S"
    )
    export_manifest["Source_Module"] = "09_Portfolio_Stress_Reporting"
    export_manifest["Target_System"] = "Power BI"
    export_manifest["Encoding"] = "UTF-8"
    export_manifest["Delimiter"] = "Comma"
    export_manifest["Header_Row"] = True

    export_sample = pd.concat(
        [
            powerbi_ecl_summary.assign(
                Export_Dataset="Executive ECL Summary"
            ),
            powerbi_product_summary.head(5).assign(
                Export_Dataset="Product ECL Summary"
            ),
            powerbi_segment_summary.head(5).assign(
                Export_Dataset="Segment ECL Summary"
            ),
        ],
        ignore_index=True,
        sort=False
    )

    validation_results.to_csv(
        EXPORT_VALIDATION_FILE,
        index=False,
        encoding="utf-8"
    )
    export_manifest.to_csv(
        EXPORT_MANIFEST_FILE,
        index=False,
        encoding="utf-8"
    )
    export_sample.to_csv(
        EXPORT_SAMPLE_FILE,
        index=False,
        encoding="utf-8"
    )

    evidence_files = [
        EXPORT_VALIDATION_FILE,
        EXPORT_MANIFEST_FILE,
        EXPORT_SAMPLE_FILE,
    ]
    if not all(file_path.exists() for file_path in evidence_files):
        raise FileNotFoundError(
            "One or more Module 10 evidence files were not created."
        )
    if not all(file_path.stat().st_size > 0 for file_path in evidence_files):
        raise ValueError(
            "One or more Module 10 evidence files are empty."
        )

    output_record_count = len(evidence_files)
    records_processed = len(export_verification)

    print("=" * 80)
    print("FINAL MODULE 10 VALIDATION")
    print("=" * 80)
    display(validation_results)

    print("\nPower BI Export Manifest:")
    display(export_manifest)

    print("Overall Module 10 Validation Status: PASS")

    logger.info(
        "Module 10 validation evidence and export manifest created successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception(
        "Block 6 failed while creating validation evidence."
    )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT FILES        :", input_record_count)
    print("EVIDENCE FILES     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 6 : CREATE VALIDATION EVIDENCE AND EXPORT MANIFEST
START TIME : 2026-10-14 03:45:33
================================================================================
================================================================================
FINAL MODULE 10 VALIDATION
================================================================================

                       Validation_Check Expected_Result Actual_Result Status
0          Executive Source File Exists            True          True   PASS
1            Product Source File Exists            True          True   PASS
2            Segment Source File Exists            True          True   PASS
3           Executive Summary Row Count               3             3   PASS
4       Executive Summary Account Total           30000         30000   PASS
5         Product Summary Account Total           30000         30000   PASS
6         Segment Summary Account Total           30000         30000   PASS
7     Executive Missing Required Values               0             0   PASS
8       Product Missing Required Values               0             0   PASS
9       Segment Missing Required Values               0             0   PASS
10             Executive Duplicate Keys               0             0   PASS
11               Product Duplicate Keys               0             0   PASS
12               Segment Duplicate Keys               0             0   PASS
13           Expected Export File Count               3             3   PASS
14           Verified Export File Count               3             3   PASS
15             Failed Export File Count               0             0   PASS
16  Numerical Reconciliation Exceptions               0             0   PASS

Power BI Export Manifest:

,Dataset_Name,File_Name,Exists,Size_Bytes,Expected_Rows,Saved_Rows,Expected_Columns,Saved_Columns,SHA256,Full_Path,Status,Export_Timestamp,Source_Module,Target_System,Encoding,Delimiter,Header_Row
0,Executive ECL Summary,ecl_summary.csv,True,342,3,3,6,6,8f61a218840a7a1cc84918d348c586b9ae25d13a680b58...,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS,2026-10-14 03:45:33,09_Portfolio_Stress_Reporting,Power BI,UTF-8,Comma,True
1,Product ECL Summary,product_ecl_summary.csv,True,1140,18,18,5,5,045e948be2b2696922467e40330c6ce51418dfd41ebe2f...,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS,2026-10-14 03:45:33,09_Portfolio_Stress_Reporting,Power BI,UTF-8,Comma,True
2,Segment ECL Summary,segment_ecl_summary.csv,True,603,9,9,5,5,164460eee5107d353d01a144f2c188c76484e0b4de8fb8...,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS,2026-10-14 03:45:33,09_Portfolio_Stress_Reporting,Power BI,UTF-8,Comma,True

Overall Module 10 Validation Status: PASS
2026-10-14 03:45:33,313 | INFO | Module 10 validation evidence and export manifest created successfully.

INFO:10_Export_For_PowerBI:Module 10 validation evidence and export manifest created successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT FILES        : 3
EVIDENCE FILES     : 3
RECORDS PROCESSED  : 3
END TIME           : 2026-10-14 03:45:33
DURATION (SECONDS) : 0.103
================================================================================

In [8]:
# =============================================================================
# CELL 08 - BLOCK 7: FINAL OUTPUT VERIFICATION AND MODULE COMPLETION
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = 0
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 10: EXPORT FOR POWER BI")
print("BLOCK 7 : FINAL OUTPUT VERIFICATION AND MODULE COMPLETION")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    final_expected_files = [
        ECL_EXPORT_FILE,
        PRODUCT_EXPORT_FILE,
        SEGMENT_EXPORT_FILE,
        EXPORT_VALIDATION_FILE,
        EXPORT_MANIFEST_FILE,
        EXPORT_SAMPLE_FILE,
        LOG_FILE,
    ]

    final_output_verification = pd.DataFrame({
        "File_Name": [
            file_path.name
            for file_path in final_expected_files
        ],
        "File_Category": [
            "Power BI Export",
            "Power BI Export",
            "Power BI Export",
            "Validation Evidence",
            "Validation Evidence",
            "Validation Evidence",
            "Execution Log",
        ],
        "Exists": [
            file_path.exists()
            for file_path in final_expected_files
        ],
        "Size_Bytes": [
            file_path.stat().st_size
            if file_path.exists()
            else 0
            for file_path in final_expected_files
        ],
        "Full_Path": [
            str(file_path)
            for file_path in final_expected_files
        ],
    })

    final_output_verification["Status"] = np.where(
        final_output_verification["Exists"]
        & (final_output_verification["Size_Bytes"] > 0),
        "PASS",
        "FAIL"
    )

    if not (final_output_verification["Status"] == "PASS").all():
        raise ValueError(
            "One or more final Module 10 files failed verification."
        )

    input_record_count = 3
    output_record_count = len(final_output_verification)
    records_processed = (
        len(powerbi_ecl_summary)
        + len(powerbi_product_summary)
        + len(powerbi_segment_summary)
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception(
        "Block 7 failed during final output verification."
    )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(),
        3
    )
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT DATASETS     :", input_record_count)
    print("VERIFIED FILES     :", output_record_count)
    print("EXPORT ROWS        :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

module_end_timestamp = datetime.now()
module_duration_seconds = round(
    (module_end_timestamp - module_start_timestamp).total_seconds(),
    3
)

print("=" * 80)
print("PYTHON V2 - MODULE 10 COMPLETED")
print("POWER BI EXPORT PROCESS COMPLETED SUCCESSFULLY")
print("=" * 80)
print("OUTPUT LOCATION:", POWERBI_DIR)
print("FILES EXPORTED:")
print("1.", ECL_EXPORT_FILE.name)
print("2.", PRODUCT_EXPORT_FILE.name)
print("3.", SEGMENT_EXPORT_FILE.name)
print("Validation Evidence:", EXPORT_VALIDATION_FILE)
print("Export Manifest:", EXPORT_MANIFEST_FILE)
print("Export Sample:", EXPORT_SAMPLE_FILE)
print("Execution Log:", LOG_FILE)

print("\nFinal Output File Verification:")
display(final_output_verification)

print("=" * 80)
print("MODULE STATUS                  : SUCCESS")
print(
    "MODULE START                   :",
    module_start_timestamp.strftime("%Y-%m-%d %H:%M:%S")
)
print(
    "MODULE END                     :",
    module_end_timestamp.strftime("%Y-%m-%d %H:%M:%S")
)
print("TOTAL DURATION (SECONDS)       :", module_duration_seconds)
print("POWER BI FILES EXPORTED        :", 3)
print("TOTAL EXPORT ROWS              :", records_processed)
print("FAILED VALIDATION CHECKS       :", len(failed_validations))
print("=" * 80)
print("BANKING STRESS TESTING PYTHON V2 FRAMEWORK COMPLETE.")
print("POWER BI REPORTING DATASETS ARE READY.")

logger.info(
    "Module 10 completed successfully in %s seconds.",
    module_duration_seconds
)

================================================================================
MODULE 10: EXPORT FOR POWER BI
BLOCK 7 : FINAL OUTPUT VERIFICATION AND MODULE COMPLETION
START TIME : 2026-10-14 03:47:37
================================================================================
================================================================================
BLOCK STATUS       : SUCCESS
INPUT DATASETS     : 3
VERIFIED FILES     : 7
EXPORT ROWS        : 30
END TIME           : 2026-10-14 03:47:37
DURATION (SECONDS) : 0.008
================================================================================
================================================================================
PYTHON V2 - MODULE 10 COMPLETED
POWER BI EXPORT PROCESS COMPLETED SUCCESSFULLY
================================================================================
OUTPUT LOCATION: /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/PowerBI
FILES EXPORTED:
1. ecl_summary.csv
2. product_ecl_summary.csv
3. segment_ecl_summary.csv
Validation Evidence: /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/validation/10_powerbi_export_validation.csv
Export Manifest: /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/validation/10_powerbi_export_manifest.csv
Export Sample: /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/validation/10_powerbi_export_sample.csv
Execution Log: /content/gdrive/MyDrive/Banking_Stress_Testing_V2_Python/logs/10_Export_For_PowerBI.log

Final Output File Verification:

,File_Name,File_Category,Exists,Size_Bytes,Full_Path,Status
0,ecl_summary.csv,Power BI Export,True,342,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
1,product_ecl_summary.csv,Power BI Export,True,1140,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
2,segment_ecl_summary.csv,Power BI Export,True,603,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
3,10_powerbi_export_validation.csv,Validation Evidence,True,736,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
4,10_powerbi_export_manifest.csv,Validation Evidence,True,1073,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
5,10_powerbi_export_sample.csv,Validation Evidence,True,1247,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS
6,10_Export_For_PowerBI.log,Execution Log,True,629,/content/gdrive/MyDrive/Banking_Stress_Testing...,PASS

================================================================================
MODULE STATUS                  : SUCCESS
MODULE START                   : 2026-10-14 03:31:41
MODULE END                     : 2026-10-14 03:47:37
TOTAL DURATION (SECONDS)       : 956.401
POWER BI FILES EXPORTED        : 3
TOTAL EXPORT ROWS              : 30
FAILED VALIDATION CHECKS       : 0
================================================================================
BANKING STRESS TESTING PYTHON V2 FRAMEWORK COMPLETE.
POWER BI REPORTING DATASETS ARE READY.
2026-10-14 03:47:37,486 | INFO | Module 10 completed successfully in 956.401 seconds.

INFO:10_Export_For_PowerBI:Module 10 completed successfully in 956.401 seconds.