In [3]:
# ==========================================================
# Banking Stress Testing Framework
# Module 02 - Data Preparation
# ==========================================================

# =============================================================================
# PROJECT       : Banking Stress Testing Framework
# VERSION       : Python V2 Migration
# MODULE        : 02 - Data Preparation
# NOTEBOOK      : 02_Data_Preparation.ipynb
# AUTHOR        : Umesh Zure
#
# PURPOSE:
# Prepare Module 01 output for downstream risk segmentation and stress testing.
#
# INPUT:
# output/portfolio_raw.csv
#
# OUTPUTS:
# output/prepared_portfolio.csv
# validation/02_data_preparation_summary.csv
# validation/02_data_preparation_validation.csv
# logs/02_Data_Preparation.log
#
# BUSINESS RULES:
# 1. Standardize categorical variables.
# 2. Impute missing Credit_Score using Customer_Segment median.
# 3. Use portfolio median as fallback for Credit_Score.
# 4. Impute missing Current_DPD with zero.
# 5. Apply valid Credit_Score and Current_DPD boundaries.
# 6. Preserve missing Collateral_Value values.
# 7. Exclude segmentation, which will be performed in Module 03.
# =============================================================================

# =============================================================================
# Banking Stress Testing Framework
# Python V2 Migration
# =============================================================================
block_start_time = datetime.now()

print("=" * 80)
print("Banking Stress Testing Framework")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

print("=" * 80)
print("BANKING STRESS TESTING FRAMEWORK")
print("PYTHON V2 - MODULE 02: DATA PREPARATION")
print("=" * 80)

block_end_time = datetime.now()

print("=" * 80)
print("BLOCK COMPLETED")
print(
    "END TIME :",
    block_end_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "DURATION :",
    block_end_time - block_start_time
)
print("=" * 80)

================================================================================
Banking Stress Testing Framework
START TIME : 2026-10-13 05:54:54
================================================================================
================================================================================
BANKING STRESS TESTING FRAMEWORK
PYTHON V2 - MODULE 02: DATA PREPARATION
================================================================================
================================================================================
BLOCK COMPLETED
END TIME : 2026-10-13 05:54:54
DURATION : 0:00:00.000524
================================================================================

In [5]:
# =============================================================================
# BLOCK 1: ENVIRONMENT AND PATH CONFIGURATION
# =============================================================================

block_start_time = datetime.now()

print("=" * 80)
print("BLOCK 1: ENVIRONMENT AND PATH CONFIGURATION")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)


from google.colab import drive
from pathlib import Path
from datetime import datetime
import logging
import sys

import numpy as np
import pandas as pd

# Mount Google Drive.
drive.mount("/content/drive")

# ---------------------------------------------------------------------------
# Project folders and files
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/Banking_Stress_Testing_V2_Python"
)

INPUT_FILE = (
    PROJECT_ROOT
    / "output"
    / "portfolio_raw.csv"
)

OUTPUT_FILE = (
    PROJECT_ROOT
    / "output"
    / "prepared_portfolio.csv"
)

VALIDATION_DIR = (
    PROJECT_ROOT
    / "validation"
)

LOG_DIR = (
    PROJECT_ROOT
    / "logs"
)

SUMMARY_FILE = (
    VALIDATION_DIR
    / "02_data_preparation_summary.csv"
)

VALIDATION_FILE = (
    VALIDATION_DIR
    / "02_data_preparation_validation.csv"
)

LOG_FILE = (
    LOG_DIR
    / "02_Data_Preparation.log"
)

# Create output directories where necessary.
OUTPUT_FILE.parent.mkdir(
    parents=True,
    exist_ok=True
)

VALIDATION_DIR.mkdir(
    parents=True,
    exist_ok=True
)

LOG_DIR.mkdir(
    parents=True,
    exist_ok=True
)

# ---------------------------------------------------------------------------
# Logging configuration
# ---------------------------------------------------------------------------

logger = logging.getLogger(
    "02_Data_Preparation"
)

logger.setLevel(
    logging.INFO
)

# Prevent duplicate logging when rerunning this cell.
if logger.hasHandlers():
    logger.handlers.clear()

log_format = logging.Formatter(
    "%(asctime)s | %(levelname)s | %(message)s"
)

file_handler = logging.FileHandler(
    LOG_FILE,
    mode="w",
    encoding="utf-8"
)

file_handler.setFormatter(
    log_format
)

console_handler = logging.StreamHandler(
    sys.stdout
)

console_handler.setFormatter(
    log_format
)

logger.addHandler(
    file_handler
)

logger.addHandler(
    console_handler
)

# ---------------------------------------------------------------------------
# Path validation
# ---------------------------------------------------------------------------

print("=" * 80)
print("ENVIRONMENT AND PATH CONFIGURATION")
print("=" * 80)

print(
    "Project Root Exists:",
    PROJECT_ROOT.exists()
)

print(
    "Module 01 Output Exists:",
    INPUT_FILE.exists()
)

print(
    "Input File:",
    INPUT_FILE
)

print(
    "Prepared Output File:",
    OUTPUT_FILE
)

print(
    "Validation Directory:",
    VALIDATION_DIR
)

print(
    "Log File:",
    LOG_FILE
)

assert PROJECT_ROOT.exists(), (
    f"Project folder was not found: {PROJECT_ROOT}"
)

assert INPUT_FILE.exists(), (
    f"Module 01 output was not found: {INPUT_FILE}"
)

logger.info(
    "Environment and path configuration completed successfully."
)


block_end_time = datetime.now()

print("=" * 80)
print("BLOCK COMPLETED")
print(
    "END TIME :",
    block_end_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "DURATION :",
    block_end_time - block_start_time
)
print("=" * 80)

================================================================================
BLOCK 1: ENVIRONMENT AND PATH CONFIGURATION
START TIME : 2026-10-13 06:04:32
================================================================================
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
================================================================================
ENVIRONMENT AND PATH CONFIGURATION
================================================================================
Project Root Exists: True
Module 01 Output Exists: True
Input File: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/portfolio_raw.csv
Prepared Output File: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/prepared_portfolio.csv
Validation Directory: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation
Log File: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/02_Data_Preparation.log
2026-10-13 06:04:34,006 | INFO | Environment and path configuration completed successfully.

INFO:02_Data_Preparation:Environment and path configuration completed successfully.

================================================================================
BLOCK COMPLETED
END TIME : 2026-10-13 06:04:34
DURATION : 0:00:01.581580
================================================================================

In [6]:
# =============================================================================
# BLOCK 2: LOAD AND VALIDATE MODULE 01 OUTPUT
# =============================================================================
block_start_time = datetime.now()

print("=" * 80)
print("BLOCK 2: LOAD AND VALIDATE MODULE 01 OUTPUT")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)


EXPECTED_COLUMNS = [
    "Customer_ID",
    "Loan_ID",
    "Customer_Segment",
    "Product_Type",
    "Outstanding_Balance",
    "Credit_Score",
    "Previous_Credit_Score",
    "Current_DPD",
    "Previous_DPD",
    "Interest_Rate",
    "Loan_Term_Months",
    "Remaining_Term_Months",
    "Collateral_Value",
    "Region",
    "Reporting_Date",
]

logger.info(
    "Starting Module 02 data preparation."
)

try:
    portfolio_raw = pd.read_csv(
        INPUT_FILE,
        low_memory=False
    )

except FileNotFoundError as error:
    logger.exception(
        "Module 01 output was not found."
    )
    raise error

except pd.errors.EmptyDataError as error:
    logger.exception(
        "Module 01 output is empty."
    )
    raise error

except pd.errors.ParserError as error:
    logger.exception(
        "Module 01 output could not be parsed."
    )
    raise error

# Create an independent preparation dataset.
prepared_portfolio = portfolio_raw.copy(
    deep=True
)

input_record_count = len(
    prepared_portfolio
)

input_column_count = len(
    prepared_portfolio.columns
)

missing_columns = sorted(
    set(EXPECTED_COLUMNS)
    - set(prepared_portfolio.columns)
)

unexpected_columns = sorted(
    set(prepared_portfolio.columns)
    - set(EXPECTED_COLUMNS)
)

if missing_columns:
    logger.error(
        "Required columns are missing: %s",
        missing_columns
    )

    raise ValueError(
        f"Required columns are missing: {missing_columns}"
    )

print("=" * 80)
print("MODULE 01 OUTPUT LOADED SUCCESSFULLY")
print("=" * 80)

print(
    "Input Records:",
    input_record_count
)

print(
    "Input Columns:",
    input_column_count
)

print(
    "Missing Required Columns:",
    missing_columns
)

print(
    "Unexpected Columns:",
    unexpected_columns
)

print(
    "Schema Status: PASS"
)

display(
    prepared_portfolio.head()
)

logger.info(
    "Module 01 output loaded: %s rows and %s columns.",
    input_record_count,
    input_column_count
)

block_end_time = datetime.now()

print("=" * 80)
print("BLOCK COMPLETED")
print(
    "END TIME :",
    block_end_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "DURATION :",
    block_end_time - block_start_time
)
print("=" * 80)

================================================================================
BLOCK 2: LOAD AND VALIDATE MODULE 01 OUTPUT
START TIME : 2026-10-13 06:07:25
================================================================================
2026-10-13 06:07:25,069 | INFO | Starting Module 02 data preparation.

INFO:02_Data_Preparation:Starting Module 02 data preparation.

================================================================================
MODULE 01 OUTPUT LOADED SUCCESSFULLY
================================================================================
Input Records: 10000
Input Columns: 15
Missing Required Columns: []
Unexpected Columns: []
Schema Status: PASS

,Customer_ID,Loan_ID,Customer_Segment,Product_Type,Outstanding_Balance,Credit_Score,Previous_Credit_Score,Current_DPD,Previous_DPD,Interest_Rate,Loan_Term_Months,Remaining_Term_Months,Collateral_Value,Region,Reporting_Date
0,1000001,50000001,Retail,Personal Loan,1733362.19,756.0,733,0.0,15,19.40,77,21,NaN,West,2026-09-30
1,1000002,50000002,Corporate,Corporate Loan,62244073.93,817.0,805,0.0,30,10.82,22,6,NaN,East,2026-09-30
2,1000003,50000003,Retail,Credit Card,303259.15,630.0,610,0.0,0,25.70,22,12,NaN,East,2026-09-30
3,1000004,50000004,SME,Auto Loan,993246.23,724.0,688,0.0,0,13.14,65,9,918420.09,West,2026-09-30
4,1000005,50000005,Retail,Personal Loan,1654985.49,784.0,761,0.0,0,16.05,25,21,NaN,South,2026-09-30

2026-10-13 06:07:25,225 | INFO | Module 01 output loaded: 10000 rows and 15 columns.

INFO:02_Data_Preparation:Module 01 output loaded: 10000 rows and 15 columns.

================================================================================
BLOCK COMPLETED
END TIME : 2026-10-13 06:07:25
DURATION : 0:00:00.163085
================================================================================

In [7]:
# =============================================================================
# BLOCK 3: CREDIT SCORE HANDLING - SAS V1 EQUIVALENT
# =============================================================================

block_start_time = datetime.now()

print("=" * 80)
print("BLOCK 3: CREDIT SCORE HANDLING - SAS V1 EQUIVALENT")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)



prepared_portfolio[
    "Credit_Score"
] = pd.to_numeric(
    prepared_portfolio["Credit_Score"],
    errors="coerce"
)

prepared_portfolio[
    "Previous_Credit_Score"
] = pd.to_numeric(
    prepared_portfolio["Previous_Credit_Score"],
    errors="coerce"
)

# Preserve source value before imputation.
prepared_portfolio[
    "Original_Credit_Score"
] = prepared_portfolio["Credit_Score"]

current_score_available = (
    prepared_portfolio["Credit_Score"].notna()
)

previous_score_available = (
    prepared_portfolio["Previous_Credit_Score"].notna()
)

score_imputation_mask = (
    prepared_portfolio["Credit_Score"].isna()
    & previous_score_available
)

score_unresolved_mask = (
    prepared_portfolio["Credit_Score"].isna()
    & prepared_portfolio["Previous_Credit_Score"].isna()
)

prepared_portfolio[
    "Credit_Score_Status"
] = np.select(
    [
        current_score_available,
        score_imputation_mask,
        score_unresolved_mask,
    ],
    [
        "Current Score Available",
        "Imputed from Previous Score",
        "Credit Score Unresolved",
    ],
    default="Credit Score Unresolved",
)

prepared_portfolio.loc[
    score_imputation_mask,
    "Credit_Score"
] = prepared_portfolio.loc[
    score_imputation_mask,
    "Previous_Credit_Score"
]

prepared_portfolio[
    "Credit_Score_Imputed_Flag"
] = np.where(
    score_imputation_mask,
    1,
    0
)

missing_credit_score_before = int(
    prepared_portfolio[
        "Original_Credit_Score"
    ].isna().sum()
)

credit_scores_imputed = int(
    score_imputation_mask.sum()
)

unresolved_credit_scores = int(
    prepared_portfolio[
        "Credit_Score"
    ].isna().sum()
)

print("=" * 80)
print("CREDIT SCORE PREPARATION COMPLETED - SAS V1 EQUIVALENT")
print("=" * 80)

print(
    "Original Missing Credit Scores:",
    missing_credit_score_before
)

print(
    "Imputed from Previous Credit Score:",
    credit_scores_imputed
)

print(
    "Final Missing Credit Scores:",
    unresolved_credit_scores
)

display(
    prepared_portfolio[
        "Credit_Score_Status"
    ]
    .value_counts(
        dropna=False
    )
    .rename_axis(
        "Credit_Score_Status"
    )
    .reset_index(
        name="Record_Count"
    )
)

display(
    prepared_portfolio.loc[
        prepared_portfolio[
            "Credit_Score_Imputed_Flag"
        ] == 1,
        [
            "Customer_ID",
            "Loan_ID",
            "Original_Credit_Score",
            "Previous_Credit_Score",
            "Credit_Score",
            "Credit_Score_Status",
        ]
    ]
    .head(10)
)

logger.info(
    "Credit Score preparation completed using SAS V1 rules. "
    "Imputed records: %s; unresolved records: %s.",
    credit_scores_imputed,
    unresolved_credit_scores,
)


block_end_time = datetime.now()

print("=" * 80)
print("BLOCK COMPLETED")
print(
    "END TIME :",
    block_end_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "DURATION :",
    block_end_time - block_start_time
)
print("=" * 80)

================================================================================
BLOCK 3: CREDIT SCORE HANDLING - SAS V1 EQUIVALENT
START TIME : 2026-10-13 06:09:48
================================================================================
================================================================================
CREDIT SCORE PREPARATION COMPLETED - SAS V1 EQUIVALENT
================================================================================
Original Missing Credit Scores: 100
Imputed from Previous Credit Score: 100
Final Missing Credit Scores: 0

           Credit_Score_Status  Record_Count
0      Current Score Available          9900
1  Imputed from Previous Score           100

,Customer_ID,Loan_ID,Original_Credit_Score,Previous_Credit_Score,Credit_Score,Credit_Score_Status
258,1000259,50000259,NaN,743,743.0,Imputed from Previous Score
383,1000384,50000384,NaN,791,791.0,Imputed from Previous Score
412,1000413,50000413,NaN,787,787.0,Imputed from Previous Score
509,1000510,50000510,NaN,552,552.0,Imputed from Previous Score
709,1000710,50000710,NaN,633,633.0,Imputed from Previous Score
881,1000882,50000882,NaN,698,698.0,Imputed from Previous Score
956,1000957,50000957,NaN,728,728.0,Imputed from Previous Score
1061,1001062,50001062,NaN,834,834.0,Imputed from Previous Score
1084,1001085,50001085,NaN,767,767.0,Imputed from Previous Score
1130,1001131,50001131,NaN,643,643.0,Imputed from Previous Score

2026-10-13 06:09:48,780 | INFO | Credit Score preparation completed using SAS V1 rules. Imputed records: 100; unresolved records: 0.

INFO:02_Data_Preparation:Credit Score preparation completed using SAS V1 rules. Imputed records: 100; unresolved records: 0.

================================================================================
BLOCK COMPLETED
END TIME : 2026-10-13 06:09:48
DURATION : 0:00:00.042658
================================================================================

In [8]:
# =============================================================================
# BLOCK 4: CURRENT DPD HANDLING - SAS V1 EQUIVALENT
# =============================================================================

block_start_time = datetime.now()

print("=" * 80)
print("BLOCK 4: CURRENT DPD HANDLING - SAS V1 EQUIVALENT")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)


prepared_portfolio[
    "Current_DPD"
] = pd.to_numeric(
    prepared_portfolio["Current_DPD"],
    errors="coerce"
)

prepared_portfolio[
    "Previous_DPD"
] = pd.to_numeric(
    prepared_portfolio["Previous_DPD"],
    errors="coerce"
)

# Preserve source value before imputation.
prepared_portfolio[
    "Original_Current_DPD"
] = prepared_portfolio["Current_DPD"]

current_dpd_available = (
    prepared_portfolio["Current_DPD"].notna()
)

previous_dpd_available = (
    prepared_portfolio["Previous_DPD"].notna()
)

dpd_imputation_mask = (
    prepared_portfolio["Current_DPD"].isna()
    & previous_dpd_available
)

dpd_unresolved_mask = (
    prepared_portfolio["Current_DPD"].isna()
    & prepared_portfolio["Previous_DPD"].isna()
)

prepared_portfolio[
    "DPD_Status"
] = np.select(
    [
        current_dpd_available,
        dpd_imputation_mask,
        dpd_unresolved_mask,
    ],
    [
        "Current DPD Available",
        "Imputed from Previous DPD",
        "Current DPD Unresolved",
    ],
    default="Current DPD Unresolved",
)

prepared_portfolio.loc[
    dpd_imputation_mask,
    "Current_DPD"
] = prepared_portfolio.loc[
    dpd_imputation_mask,
    "Previous_DPD"
]

# Invalid negative DPD is converted to missing after imputation.
negative_dpd_mask = (
    prepared_portfolio["Current_DPD"].notna()
    & (prepared_portfolio["Current_DPD"] < 0)
)

prepared_portfolio.loc[
    negative_dpd_mask,
    "Current_DPD"
] = np.nan

prepared_portfolio.loc[
    negative_dpd_mask,
    "DPD_Status"
] = "Invalid Negative DPD"

prepared_portfolio[
    "Current_DPD_Imputed_Flag"
] = np.where(
    dpd_imputation_mask,
    1,
    0
)

missing_current_dpd_before = int(
    prepared_portfolio[
        "Original_Current_DPD"
    ].isna().sum()
)

current_dpd_imputed = int(
    dpd_imputation_mask.sum()
)

invalid_negative_dpd = int(
    negative_dpd_mask.sum()
)

unresolved_current_dpd = int(
    prepared_portfolio[
        "Current_DPD"
    ].isna().sum()
)

print("=" * 80)
print("CURRENT DPD PREPARATION COMPLETED - SAS V1 EQUIVALENT")
print("=" * 80)

print(
    "Original Missing Current DPD:",
    missing_current_dpd_before
)

print(
    "Imputed from Previous DPD:",
    current_dpd_imputed
)

print(
    "Invalid Negative DPD:",
    invalid_negative_dpd
)

print(
    "Final Missing Current DPD:",
    unresolved_current_dpd
)

display(
    prepared_portfolio[
        "DPD_Status"
    ]
    .value_counts(
        dropna=False
    )
    .rename_axis(
        "DPD_Status"
    )
    .reset_index(
        name="Record_Count"
    )
)

display(
    prepared_portfolio.loc[
        prepared_portfolio[
            "Current_DPD_Imputed_Flag"
        ] == 1,
        [
            "Customer_ID",
            "Loan_ID",
            "Original_Current_DPD",
            "Previous_DPD",
            "Current_DPD",
            "DPD_Status",
        ]
    ]
    .head(10)
)

logger.info(
    "Current DPD preparation completed using SAS V1 rules. "
    "Imputed records: %s; unresolved records: %s.",
    current_dpd_imputed,
    unresolved_current_dpd,
)



block_end_time = datetime.now()

print("=" * 80)
print("BLOCK COMPLETED")
print(
    "END TIME :",
    block_end_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "DURATION :",
    block_end_time - block_start_time
)
print("=" * 80)

================================================================================
BLOCK 4: CURRENT DPD HANDLING - SAS V1 EQUIVALENT
START TIME : 2026-10-13 06:12:39
================================================================================
================================================================================
CURRENT DPD PREPARATION COMPLETED - SAS V1 EQUIVALENT
================================================================================
Original Missing Current DPD: 75
Imputed from Previous DPD: 75
Invalid Negative DPD: 0
Final Missing Current DPD: 0

                  DPD_Status  Record_Count
0      Current DPD Available          9925
1  Imputed from Previous DPD            75

,Customer_ID,Loan_ID,Original_Current_DPD,Previous_DPD,Current_DPD,DPD_Status
58,1000059,50000059,NaN,15,15.0,Imputed from Previous DPD
188,1000189,50000189,NaN,0,0.0,Imputed from Previous DPD
200,1000201,50000201,NaN,0,0.0,Imputed from Previous DPD
524,1000525,50000525,NaN,0,0.0,Imputed from Previous DPD
701,1000702,50000702,NaN,0,0.0,Imputed from Previous DPD
733,1000734,50000734,NaN,0,0.0,Imputed from Previous DPD
756,1000757,50000757,NaN,0,0.0,Imputed from Previous DPD
812,1000813,50000813,NaN,15,15.0,Imputed from Previous DPD
866,1000867,50000867,NaN,15,15.0,Imputed from Previous DPD
1191,1001192,50001192,NaN,0,0.0,Imputed from Previous DPD

2026-10-13 06:12:39,703 | INFO | Current DPD preparation completed using SAS V1 rules. Imputed records: 75; unresolved records: 0.

INFO:02_Data_Preparation:Current DPD preparation completed using SAS V1 rules. Imputed records: 75; unresolved records: 0.

================================================================================
BLOCK COMPLETED
END TIME : 2026-10-13 06:12:39
DURATION : 0:00:00.042722
================================================================================

In [9]:
# =============================================================================
# BLOCK 5: STANDARDIZATION AND BASIC BUSINESS VALIDATION
# =============================================================================

block_start_time = datetime.now()

print("=" * 80)
print("BLOCK 5: STANDARDIZATION AND BASIC BUSINESS VALIDATION")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)


categorical_columns = [
    "Customer_Segment",
    "Product_Type",
    "Region",
]

# Trim leading and trailing spaces and reduce repeated spaces.
for column in categorical_columns:
    prepared_portfolio[column] = (
        prepared_portfolio[column]
        .astype("string")
        .str.strip()
        .str.replace(
            r"\s+",
            " ",
            regex=True
        )
    )

# Controlled canonical values.
segment_map = {
    "RETAIL": "Retail",
    "SME": "SME",
    "CORPORATE": "Corporate",
}

product_map = {
    "MORTGAGE": "Mortgage",
    "AUTO LOAN": "Auto Loan",
    "PERSONAL LOAN": "Personal Loan",
    "CREDIT CARD": "Credit Card",
    "SME LOAN": "SME Loan",
    "CORPORATE LOAN": "Corporate Loan",
}

region_map = {
    "NORTH": "North",
    "SOUTH": "South",
    "EAST": "East",
    "WEST": "West",
    "CENTRAL": "Central",
}

prepared_portfolio[
    "Customer_Segment"
] = (
    prepared_portfolio[
        "Customer_Segment"
    ]
    .str.upper()
    .map(segment_map)
)

prepared_portfolio[
    "Product_Type"
] = (
    prepared_portfolio[
        "Product_Type"
    ]
    .str.upper()
    .map(product_map)
)

prepared_portfolio[
    "Region"
] = (
    prepared_portfolio[
        "Region"
    ]
    .str.upper()
    .map(region_map)
)

# Convert Reporting_Date to datetime.
prepared_portfolio[
    "Reporting_Date"
] = pd.to_datetime(
    prepared_portfolio[
        "Reporting_Date"
    ],
    errors="coerce"
)

# Ensure supporting fields are numeric.
numeric_columns = [
    "Outstanding_Balance",
    "Previous_Credit_Score",
    "Previous_DPD",
    "Interest_Rate",
    "Loan_Term_Months",
    "Remaining_Term_Months",
    "Collateral_Value",
]

for column in numeric_columns:
    prepared_portfolio[column] = pd.to_numeric(
        prepared_portfolio[column],
        errors="coerce"
    )

invalid_segments = int(
    prepared_portfolio[
        "Customer_Segment"
    ]
    .isna()
    .sum()
)

invalid_products = int(
    prepared_portfolio[
        "Product_Type"
    ]
    .isna()
    .sum()
)

invalid_regions = int(
    prepared_portfolio[
        "Region"
    ]
    .isna()
    .sum()
)

invalid_reporting_dates = int(
    prepared_portfolio[
        "Reporting_Date"
    ]
    .isna()
    .sum()
)

invalid_balances = int(
    (
        prepared_portfolio[
            "Outstanding_Balance"
        ] <= 0
    )
    .sum()
)

invalid_remaining_terms = int(
    (
        prepared_portfolio[
            "Remaining_Term_Months"
        ] < 0
    )
    .sum()
)

remaining_above_total_term = int(
    (
        prepared_portfolio[
            "Remaining_Term_Months"
        ]
        >
        prepared_portfolio[
            "Loan_Term_Months"
        ]
    )
    .sum()
)

secured_product_mask = (
    prepared_portfolio[
        "Product_Type"
    ]
    .isin(
        [
            "Mortgage",
            "Auto Loan",
        ]
    )
)

secured_account_count = int(
    secured_product_mask.sum()
)

missing_secured_collateral = int(
    (
        secured_product_mask
        &
        prepared_portfolio[
            "Collateral_Value"
        ].isna()
    )
    .sum()
)

# Audit flag only. Collateral is not imputed.
prepared_portfolio[
    "Secured_Collateral_Missing_Flag"
] = np.where(
    secured_product_mask
    &
    prepared_portfolio[
        "Collateral_Value"
    ].isna(),
    1,
    0
)

print("=" * 80)
print("STANDARDIZATION AND BUSINESS VALIDATION COMPLETED")
print("=" * 80)

print(
    "Invalid Customer Segments:",
    invalid_segments
)

print(
    "Invalid Product Types:",
    invalid_products
)

print(
    "Invalid Regions:",
    invalid_regions
)

print(
    "Invalid Reporting Dates:",
    invalid_reporting_dates
)

print(
    "Invalid Outstanding Balances:",
    invalid_balances
)

print(
    "Negative Remaining Terms:",
    invalid_remaining_terms
)

print(
    "Remaining Term Above Total Term:",
    remaining_above_total_term
)

print(
    "Secured Accounts:",
    secured_account_count
)

print(
    "Missing Secured Collateral:",
    missing_secured_collateral
)

print(
    "Collateral Imputation Performed: No"
)

display(
    prepared_portfolio[
        categorical_columns
    ]
    .drop_duplicates()
    .sort_values(
        categorical_columns
    )
)

logger.info(
    "Standardization and basic validation completed."
)

block_end_time = datetime.now()

print("=" * 80)
print("BLOCK COMPLETED")
print(
    "END TIME :",
    block_end_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "DURATION :",
    block_end_time - block_start_time
)
print("=" * 80)

================================================================================
BLOCK 5: STANDARDIZATION AND BASIC BUSINESS VALIDATION
START TIME : 2026-10-13 06:15:01
================================================================================
================================================================================
STANDARDIZATION AND BUSINESS VALIDATION COMPLETED
================================================================================
Invalid Customer Segments: 0
Invalid Product Types: 0
Invalid Regions: 0
Invalid Reporting Dates: 0
Invalid Outstanding Balances: 0
Negative Remaining Terms: 0
Remaining Term Above Total Term: 0
Secured Accounts: 4638
Missing Secured Collateral: 40
Collateral Imputation Performed: No

     Customer_Segment    Product_Type   Region
146         Corporate  Corporate Loan  Central
1           Corporate  Corporate Loan     East
401         Corporate  Corporate Loan    North
13          Corporate  Corporate Loan    South
140         Corporate  Corporate Loan     West
907         Corporate        Mortgage  Central
5700        Corporate        Mortgage     East
914         Corporate        Mortgage    North
314         Corporate        Mortgage    South
64          Corporate        Mortgage     West
20             Retail       Auto Loan  Central
10             Retail       Auto Loan     East
45             Retail       Auto Loan    North
22             Retail       Auto Loan    South
6              Retail       Auto Loan     West
167            Retail     Credit Card  Central
2              Retail     Credit Card     East
14             Retail     Credit Card    North
8              Retail     Credit Card    South
5              Retail     Credit Card     West
23             Retail        Mortgage  Central
37             Retail        Mortgage     East
24             Retail        Mortgage    North
11             Retail        Mortgage    South
9              Retail        Mortgage     West
78             Retail   Personal Loan  Central
59             Retail   Personal Loan     East
31             Retail   Personal Loan    North
4              Retail   Personal Loan    South
0              Retail   Personal Loan     West
33                SME       Auto Loan  Central
172               SME       Auto Loan     East
257               SME       Auto Loan    North
35                SME       Auto Loan    South
3                 SME       Auto Loan     West
34                SME        Mortgage  Central
134               SME        Mortgage     East
128               SME        Mortgage    North
40                SME        Mortgage    South
32                SME        Mortgage     West
58                SME        SME Loan  Central
25                SME        SME Loan     East
36                SME        SME Loan    North
7                 SME        SME Loan    South
26                SME        SME Loan     West

2026-10-13 06:15:01,621 | INFO | Standardization and basic validation completed.

INFO:02_Data_Preparation:Standardization and basic validation completed.

================================================================================
BLOCK COMPLETED
END TIME : 2026-10-13 06:15:01
DURATION : 0:00:00.083412
================================================================================

In [11]:
# =============================================================================
# BLOCK 6: FINAL VALIDATION AND PREPARATION SUMMARY
# =============================================================================


block_start_time = datetime.now()

print("=" * 80)
print("BLOCK 6: FINAL VALIDATION AND PREPARATION SUMMARY")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)



output_record_count = len(
    prepared_portfolio
)

output_column_count = len(
    prepared_portfolio.columns
)

final_missing_credit_score = int(
    prepared_portfolio[
        "Credit_Score"
    ]
    .isna()
    .sum()
)

final_missing_current_dpd = int(
    prepared_portfolio[
        "Current_DPD"
    ]
    .isna()
    .sum()
)

duplicate_customer_ids = int(
    prepared_portfolio[
        "Customer_ID"
    ]
    .duplicated()
    .sum()
)

duplicate_loan_ids = int(
    prepared_portfolio[
        "Loan_ID"
    ]
    .duplicated()
    .sum()
)

validation_results = pd.DataFrame({
    "Validation_Check": [
        "Input and Output Record Count",
        "Missing Credit_Score After Preparation",
        "Missing Current_DPD After Preparation",
        "Duplicate Customer_ID",
        "Duplicate Loan_ID",
        "Invalid Reporting_Date",
    ],
    "Expected_Result": [
        input_record_count,
        0,
        0,
        0,
        0,
        0,
    ],
    "Actual_Result": [
        output_record_count,
        final_missing_credit_score,
        final_missing_current_dpd,
        duplicate_customer_ids,
        duplicate_loan_ids,
        invalid_reporting_dates,
    ],
})

validation_results[
    "Status"
] = np.where(
    validation_results[
        "Expected_Result"
    ]
    ==
    validation_results[
        "Actual_Result"
    ],
    "PASS",
    "FAIL"
)

processing_timestamp = datetime.now()

preparation_summary = pd.DataFrame({
    "Metric": [
        "Input Records",
        "Output Records",
        "Input Columns",
        "Output Columns",
        "Credit Scores Imputed",
        "Current DPD Values Imputed",
        "Unresolved Credit Scores",
        "Unresolved Current DPD",
        "Secured Accounts",
        "Missing Secured Collateral",
        "Processing Timestamp"
    ],
    "Result": [
        input_record_count,
        output_record_count,
        input_column_count,
        output_column_count,
        credit_scores_imputed,
        current_dpd_imputed,
        unresolved_credit_scores,
        unresolved_current_dpd,
        secured_account_count,
        missing_secured_collateral,
        datetime.now()
    ]
})

print("=" * 80)
print("FINAL DATA PREPARATION VALIDATION")
print("=" * 80)

display(
    validation_results
)

print("\nData Preparation Summary:")

display(
    preparation_summary
)

failed_checks = validation_results.loc[
    validation_results[
        "Status"
    ] != "PASS"
]

if not failed_checks.empty:
    logger.error(
        "Module 02 final validation failed."
    )

    raise ValueError(
        "Module 02 validation failed. "
        "Review the failed checks."
    )

print(
    "Overall Module 02 Validation Status: PASS"
)

logger.info(
    "All Module 02 validation checks passed."
)


block_end_time = datetime.now()

print("=" * 80)
print("BLOCK COMPLETED")
print(
    "END TIME :",
    block_end_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "DURATION :",
    block_end_time - block_start_time
)
print("=" * 80)

================================================================================
BLOCK 6: FINAL VALIDATION AND PREPARATION SUMMARY
START TIME : 2026-10-13 06:33:00
================================================================================
================================================================================
FINAL DATA PREPARATION VALIDATION
================================================================================

,Validation_Check,Expected_Result,Actual_Result,Status
0,Input and Output Record Count,10000,10000,PASS
1,Missing Credit_Score After Preparation,0,0,PASS
2,Missing Current_DPD After Preparation,0,0,PASS
3,Duplicate Customer_ID,0,0,PASS
4,Duplicate Loan_ID,0,0,PASS
5,Invalid Reporting_Date,0,0,PASS

Data Preparation Summary:

                        Metric                      Result
0                Input Records                       10000
1               Output Records                       10000
2                Input Columns                          15
3               Output Columns                          22
4        Credit Scores Imputed                         100
5   Current DPD Values Imputed                          75
6     Unresolved Credit Scores                           0
7       Unresolved Current DPD                           0
8             Secured Accounts                        4638
9   Missing Secured Collateral                          40
10        Processing Timestamp  2026-10-13 06:33:00.751054

Overall Module 02 Validation Status: PASS
2026-10-13 06:33:00,780 | INFO | All Module 02 validation checks passed.

INFO:02_Data_Preparation:All Module 02 validation checks passed.

================================================================================
BLOCK COMPLETED
END TIME : 2026-10-13 06:33:00
DURATION : 0:00:00.038103
================================================================================

In [13]:
# =============================================================================
# BLOCK 7: SAVE OUTPUTS AND VERIFY FILES
# =============================================================================

block_start_time = datetime.now()

print("=" * 80)
print("BLOCK 7: SAVE OUTPUTS AND VERIFY FILES")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)


try:
    # Save prepared portfolio.
    prepared_portfolio.to_csv(
        OUTPUT_FILE,
        index=False,
        date_format="%Y-%m-%d"
    )

    # Save preparation-level metrics.
    preparation_summary.to_csv(
        SUMMARY_FILE,
        index=False
    )

    # Save final validation evidence.
    validation_results.to_csv(
        VALIDATION_FILE,
        index=False
    )

except Exception as error:
    logger.exception(
        "Failed to save Module 02 outputs."
    )
    raise error

expected_files = [
    OUTPUT_FILE,
    SUMMARY_FILE,
    VALIDATION_FILE,
    LOG_FILE,
]

output_verification = pd.DataFrame({
    "File_Name": [
        file_path.name
        for file_path in expected_files
    ],
    "Exists": [
        file_path.exists()
        for file_path in expected_files
    ],
    "Size_Bytes": [
        (
            file_path.stat().st_size
            if file_path.exists()
            else 0
        )
        for file_path in expected_files
    ],
    "Full_Path": [
        str(file_path)
        for file_path in expected_files
    ],
})

logger.info(
    "Prepared portfolio saved successfully."
)

logger.info(
    "Module 02 completed successfully."
)

print("=" * 80)
print("PYTHON V2 - MODULE 02 COMPLETED")
print("DATA PREPARATION EXECUTED SUCCESSFULLY")
print("=" * 80)

print(
    "Input Records:",
    input_record_count
)

print(
    "Output Records:",
    output_record_count
)

print(
    "Credit Scores Imputed:",
    credit_scores_imputed
)

print(
    "Current DPD Values Imputed:",
    current_dpd_imputed
)

print(
    "Missing Secured Collateral Preserved:",
    missing_secured_collateral
)

print(
    "Prepared Output:",
    OUTPUT_FILE
)

print(
    "Preparation Summary:",
    SUMMARY_FILE
)

print(
    "Validation Evidence:",
    VALIDATION_FILE
)

print(
    "Execution Log:",
    LOG_FILE
)

print("=" * 80)

display(
    output_verification
)

assert output_verification[
    "Exists"
].all(), (
    "One or more Module 02 output files were not created."
)

print(
    "All Module 02 output files verified successfully."
)


module_end_timestamp = datetime.now()

print("=" * 80)
print("MODULE COMPLETED SUCCESSFULLY")
print(
    "START TIME :",
    module_start_timestamp.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "END TIME :",
    module_end_timestamp.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "TOTAL DURATION :",
    module_end_timestamp -
    module_start_timestamp
)
print("=" * 80)

================================================================================
BLOCK 7: SAVE OUTPUTS AND VERIFY FILES
START TIME : 2026-10-13 06:40:11
================================================================================
2026-10-13 06:40:12,137 | INFO | Prepared portfolio saved successfully.

INFO:02_Data_Preparation:Prepared portfolio saved successfully.

2026-10-13 06:40:12,140 | INFO | Module 02 completed successfully.

INFO:02_Data_Preparation:Module 02 completed successfully.

================================================================================
PYTHON V2 - MODULE 02 COMPLETED
DATA PREPARATION EXECUTED SUCCESSFULLY
================================================================================
Input Records: 10000
Output Records: 10000
Credit Scores Imputed: 100
Current DPD Values Imputed: 75
Missing Secured Collateral Preserved: 40
Prepared Output: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/prepared_portfolio.csv
Preparation Summary: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/02_data_preparation_summary.csv
Validation Evidence: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/02_data_preparation_validation.csv
Execution Log: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/02_Data_Preparation.log
================================================================================

,File_Name,Exists,Size_Bytes,Full_Path
0,prepared_portfolio.csv,True,1581214,/content/drive/MyDrive/Banking_Stress_Testing_...
1,02_data_preparation_summary.csv,True,298,/content/drive/MyDrive/Banking_Stress_Testing_...
2,02_data_preparation_validation.csv,True,286,/content/drive/MyDrive/Banking_Stress_Testing_...
3,02_Data_Preparation.log,True,804,/content/drive/MyDrive/Banking_Stress_Testing_...

All Module 02 output files verified successfully.
================================================================================
MODULE COMPLETED SUCCESSFULLY
START TIME : 2026-10-13 05:38:48
END TIME : 2026-10-13 06:40:12
TOTAL DURATION : 1:01:23.413448
================================================================================