In [1]:
# =============================================================================
# PROJECT       : Banking Stress Testing Framework
# VERSION       : Python V2 Migration
# MODULE        : 04 - Scenario Creation
# NOTEBOOK      : 04_Scenario_Creation.ipynb
# AUTHOR        : Umesh Zure
#
# PURPOSE:
# Create and validate the macroeconomic stress-scenario master dataset using
# the exact business assumptions defined in the SAS V1 golden reference.
#
# OUTPUTS:
# output/scenario_master.csv
# validation/04_scenario_creation_summary.csv
# validation/04_scenario_creation_validation.csv
# validation/04_scenario_variable_statistics.csv
# logs/04_Scenario_Creation.log
#
# SAS V1 SCENARIOS:
#
# Scenario_ID  Scenario_Name   GDP  Unemployment  Interest  HPI Change
# 1            Baseline          6       5            6          0
# 2            Mild_Stress       3       7            8        -10
# 3            Severe_Stress    -2      10           11        -25
#
# IMPORTANT:
# This module creates the scenario master only.
# Scenarios will be applied to portfolio records in Module 05.
# =============================================================================

from datetime import datetime

module_start_timestamp = datetime.now()

print("=" * 80)
print("BANKING STRESS TESTING FRAMEWORK")
print("PYTHON V2 MIGRATION")
print("MODULE : 04_SCENARIO_CREATION")
print(
    "EXECUTION STARTED :",
    module_start_timestamp.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

================================================================================
BANKING STRESS TESTING FRAMEWORK
PYTHON V2 MIGRATION
MODULE : 04_SCENARIO_CREATION
EXECUTION STARTED : 2026-10-13 10:23:38
================================================================================

In [2]:
# =============================================================================
# BLOCK 1: ENVIRONMENT, PATHS, AND LOGGING
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
records_processed = 0

print("=" * 80)
print("MODULE 04: SCENARIO CREATION")
print("BLOCK 1 : ENVIRONMENT, PATHS, AND LOGGING")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

try:
    from google.colab import drive
    from pathlib import Path
    import logging
    import sys

    import numpy as np
    import pandas as pd

    drive.mount(
        "/content/drive"
    )

    PROJECT_ROOT = Path(
        "/content/drive/MyDrive/"
        "Banking_Stress_Testing_V2_Python"
    )

    OUTPUT_FILE = (
        PROJECT_ROOT
        / "output"
        / "scenario_master.csv"
    )

    VALIDATION_DIR = (
        PROJECT_ROOT
        / "validation"
    )

    LOG_DIR = (
        PROJECT_ROOT
        / "logs"
    )

    SUMMARY_FILE = (
        VALIDATION_DIR
        / "04_scenario_creation_summary.csv"
    )

    VALIDATION_FILE = (
        VALIDATION_DIR
        / "04_scenario_creation_validation.csv"
    )

    STATISTICS_FILE = (
        VALIDATION_DIR
        / "04_scenario_variable_statistics.csv"
    )

    LOG_FILE = (
        LOG_DIR
        / "04_Scenario_Creation.log"
    )

    OUTPUT_FILE.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    VALIDATION_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    LOG_DIR.mkdir(
        parents=True,
        exist_ok=True
    )

    logger = logging.getLogger(
        "04_Scenario_Creation"
    )

    logger.setLevel(
        logging.INFO
    )

    if logger.hasHandlers():
        logger.handlers.clear()

    log_formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s"
    )

    file_handler = logging.FileHandler(
        LOG_FILE,
        mode="w",
        encoding="utf-8"
    )

    file_handler.setFormatter(
        log_formatter
    )

    console_handler = logging.StreamHandler(
        sys.stdout
    )

    console_handler.setFormatter(
        log_formatter
    )

    logger.addHandler(
        file_handler
    )

    logger.addHandler(
        console_handler
    )

    if not PROJECT_ROOT.exists():
        raise FileNotFoundError(
            f"Project root was not found: {PROJECT_ROOT}"
        )

    print(
        "Project Root Exists:",
        PROJECT_ROOT.exists()
    )

    print(
        "Scenario Output:",
        OUTPUT_FILE
    )

    print(
        "Validation Directory:",
        VALIDATION_DIR
    )

    print(
        "Summary File:",
        SUMMARY_FILE
    )

    print(
        "Statistics File:",
        STATISTICS_FILE
    )

    print(
        "Execution Log:",
        LOG_FILE
    )

    logger.info(
        "Environment, paths, and logging configured successfully."
    )

    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"

    if "logger" in locals():
        logger.exception(
            "Block 1 failed during environment configuration."
        )

    raise

finally:
    block_end_time = datetime.now()

    block_duration_seconds = round(
        (
            block_end_time
            - block_start_time
        ).total_seconds(),
        3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("RECORDS PROCESSED  :", records_processed)
    print(
        "END TIME           :",
        block_end_time.strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )
    print(
        "DURATION (SECONDS) :",
        block_duration_seconds
    )
    print("=" * 80)

================================================================================
MODULE 04: SCENARIO CREATION
BLOCK 1 : ENVIRONMENT, PATHS, AND LOGGING
START TIME : 2026-10-13 10:26:21
================================================================================
Mounted at /content/drive
Project Root Exists: True
Scenario Output: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/scenario_master.csv
Validation Directory: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation
Summary File: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/04_scenario_creation_summary.csv
Statistics File: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/04_scenario_variable_statistics.csv
Execution Log: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/04_Scenario_Creation.log
2026-10-13 10:26:53,789 | INFO | Environment, paths, and logging configured successfully.

INFO:04_Scenario_Creation:Environment, paths, and logging configured successfully.

================================================================================
BLOCK STATUS       : SUCCESS
RECORDS PROCESSED  : 0
END TIME           : 2026-10-13 10:26:53
DURATION (SECONDS) : 32.024
================================================================================

In [4]:
# =============================================================================
# BLOCK 2: DEFINE SAS V1 SCENARIO ASSUMPTIONS
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
records_processed = 0

print("=" * 80)
print("MODULE 04: SCENARIO CREATION")
print("BLOCK 2 : DEFINE SAS V1 SCENARIO ASSUMPTIONS")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

try:
    # Exact assumptions from the SAS V1 golden reference.
    scenario_assumptions = [
        {
            "Scenario_ID": 1,
            "Scenario_Name": "Baseline",
            "GDP_Growth": 6.0,
            "Unemployment_Rate": 5.0,
            "Interest_Rate": 6.0,
            "HPI_Change": 0.0,
        },
        {
            "Scenario_ID": 2,
            "Scenario_Name": "Mild_Stress",
            "GDP_Growth": 3.0,
            "Unemployment_Rate": 7.0,
            "Interest_Rate": 8.0,
            "HPI_Change": -10.0,
        },
        {
            "Scenario_ID": 3,
            "Scenario_Name": "Severe_Stress",
            "GDP_Growth": -2.0,
            "Unemployment_Rate": 10.0,
            "Interest_Rate": 11.0,
            "HPI_Change": -25.0,
        },
    ]

    expected_scenario_count = 3

    expected_scenario_names = [
        "Baseline",
        "Mild_Stress",
        "Severe_Stress",
    ]

    required_columns = [
        "Scenario_ID",
        "Scenario_Name",
        "GDP_Growth",
        "Unemployment_Rate",
        "Interest_Rate",
        "HPI_Change",
    ]

    records_processed = len(
        scenario_assumptions
    )

    print(
        "Expected Scenario Count:",
        expected_scenario_count
    )

    print(
        "Defined Scenario Count:",
        records_processed
    )

    print(
        "Expected Scenario Names:",
        expected_scenario_names
    )

    print(
        "Required Output Columns:",
        required_columns
    )

    if records_processed != expected_scenario_count:
        raise ValueError(
            "The scenario assumptions do not contain "
            "the expected three scenarios."
        )

    logger.info(
        "SAS V1 scenario assumptions defined successfully."
    )

    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"

    logger.exception(
        "Block 2 failed while defining scenario assumptions."
    )

    raise

finally:
    block_end_time = datetime.now()

    block_duration_seconds = round(
        (
            block_end_time
            - block_start_time
        ).total_seconds(),
        3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("RECORDS PROCESSED  :", records_processed)
    print(
        "END TIME           :",
        block_end_time.strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )
    print(
        "DURATION (SECONDS) :",
        block_duration_seconds
    )
    print("=" * 80)

================================================================================
MODULE 04: SCENARIO CREATION
BLOCK 2 : DEFINE SAS V1 SCENARIO ASSUMPTIONS
START TIME : 2026-10-13 10:28:00
================================================================================
Expected Scenario Count: 3
Defined Scenario Count: 3
Expected Scenario Names: ['Baseline', 'Mild_Stress', 'Severe_Stress']
Required Output Columns: ['Scenario_ID', 'Scenario_Name', 'GDP_Growth', 'Unemployment_Rate', 'Interest_Rate', 'HPI_Change']
2026-10-13 10:28:00,217 | INFO | SAS V1 scenario assumptions defined successfully.

INFO:04_Scenario_Creation:SAS V1 scenario assumptions defined successfully.

================================================================================
BLOCK STATUS       : SUCCESS
RECORDS PROCESSED  : 3
END TIME           : 2026-10-13 10:28:00
DURATION (SECONDS) : 0.009
================================================================================

In [5]:
# =============================================================================
# BLOCK 3: CREATE SCENARIO MASTER DATASET
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(
    scenario_assumptions
)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 04: SCENARIO CREATION")
print("BLOCK 3 : CREATE SCENARIO MASTER DATASET")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

try:
    scenario_master = pd.DataFrame(
        scenario_assumptions,
        columns=required_columns
    )

    scenario_master[
        "Scenario_ID"
    ] = pd.to_numeric(
        scenario_master[
            "Scenario_ID"
        ],
        errors="raise"
    ).astype("int64")

    scenario_master[
        "Scenario_Name"
    ] = scenario_master[
        "Scenario_Name"
    ].astype("string")

    numeric_scenario_columns = [
        "GDP_Growth",
        "Unemployment_Rate",
        "Interest_Rate",
        "HPI_Change",
    ]

    for column in numeric_scenario_columns:
        scenario_master[column] = pd.to_numeric(
            scenario_master[column],
            errors="raise"
        ).astype("float64")

    output_record_count = len(
        scenario_master
    )

    records_processed = output_record_count

    print("=" * 80)
    print("SCENARIO MASTER DATASET CREATED")
    print("=" * 80)

    print(
        "Input Records:",
        input_record_count
    )

    print(
        "Output Records:",
        output_record_count
    )

    print(
        "Output Columns:",
        len(scenario_master.columns)
    )

    display(
        scenario_master
    )

    logger.info(
        "Scenario master dataset created with "
        "%s scenarios and %s columns.",
        output_record_count,
        len(scenario_master.columns)
    )

    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"

    logger.exception(
        "Block 3 failed while creating scenario master."
    )

    raise

finally:
    block_end_time = datetime.now()

    block_duration_seconds = round(
        (
            block_end_time
            - block_start_time
        ).total_seconds(),
        3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print(
        "END TIME           :",
        block_end_time.strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )
    print(
        "DURATION (SECONDS) :",
        block_duration_seconds
    )
    print("=" * 80)

================================================================================
MODULE 04: SCENARIO CREATION
BLOCK 3 : CREATE SCENARIO MASTER DATASET
START TIME : 2026-10-13 10:28:51
================================================================================
================================================================================
SCENARIO MASTER DATASET CREATED
================================================================================
Input Records: 3
Output Records: 3
Output Columns: 6

,Scenario_ID,Scenario_Name,GDP_Growth,Unemployment_Rate,Interest_Rate,HPI_Change
0,1,Baseline,6.0,5.0,6.0,0.0
1,2,Mild_Stress,3.0,7.0,8.0,-10.0
2,3,Severe_Stress,-2.0,10.0,11.0,-25.0

2026-10-13 10:28:51,594 | INFO | Scenario master dataset created with 3 scenarios and 6 columns.

INFO:04_Scenario_Creation:Scenario master dataset created with 3 scenarios and 6 columns.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 3
OUTPUT RECORDS     : 3
RECORDS PROCESSED  : 3
END TIME           : 2026-10-13 10:28:51
DURATION (SECONDS) : 0.052
================================================================================

In [6]:
# =============================================================================
# BLOCK 4: METADATA AND UNIQUENESS VALIDATION
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(
    scenario_master
)
output_record_count = input_record_count
records_processed = 0

print("=" * 80)
print("MODULE 04: SCENARIO CREATION")
print("BLOCK 4 : METADATA AND UNIQUENESS VALIDATION")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

try:
    missing_required_columns = sorted(
        set(required_columns)
        - set(scenario_master.columns)
    )

    unexpected_columns = sorted(
        set(scenario_master.columns)
        - set(required_columns)
    )

    duplicate_scenario_ids = int(
        scenario_master[
            "Scenario_ID"
        ]
        .duplicated()
        .sum()
    )

    duplicate_scenario_names = int(
        scenario_master[
            "Scenario_Name"
        ]
        .duplicated()
        .sum()
    )

    missing_value_count = int(
        scenario_master[
            required_columns
        ]
        .isna()
        .sum()
        .sum()
    )

    actual_scenario_names = (
        scenario_master[
            "Scenario_Name"
        ]
        .tolist()
    )

    scenario_name_match = (
        actual_scenario_names
        == expected_scenario_names
    )

    scenario_metadata = pd.DataFrame({
        "Column_Name": scenario_master.columns,
        "Python_Data_Type": [
            str(data_type)
            for data_type
            in scenario_master.dtypes
        ],
        "Non_Missing_Count": [
            int(
                scenario_master[column]
                .notna()
                .sum()
            )
            for column
            in scenario_master.columns
        ],
        "Missing_Count": [
            int(
                scenario_master[column]
                .isna()
                .sum()
            )
            for column
            in scenario_master.columns
        ],
        "Unique_Values": [
            int(
                scenario_master[column]
                .nunique(
                    dropna=True
                )
            )
            for column
            in scenario_master.columns
        ],
    })

    if missing_required_columns:
        raise ValueError(
            "Required scenario columns are missing: "
            f"{missing_required_columns}"
        )

    if duplicate_scenario_ids > 0:
        raise ValueError(
            "Duplicate Scenario_ID values were found."
        )

    if duplicate_scenario_names > 0:
        raise ValueError(
            "Duplicate Scenario_Name values were found."
        )

    if missing_value_count > 0:
        raise ValueError(
            "Missing scenario values were found."
        )

    if not scenario_name_match:
        raise ValueError(
            "Scenario names or ordering do not match SAS V1."
        )

    records_processed = input_record_count

    print("=" * 80)
    print("METADATA AND UNIQUENESS VALIDATION")
    print("=" * 80)

    print(
        "Missing Required Columns:",
        missing_required_columns
    )

    print(
        "Unexpected Columns:",
        unexpected_columns
    )

    print(
        "Duplicate Scenario IDs:",
        duplicate_scenario_ids
    )

    print(
        "Duplicate Scenario Names:",
        duplicate_scenario_names
    )

    print(
        "Missing Scenario Values:",
        missing_value_count
    )

    print(
        "Scenario Names Match SAS V1:",
        scenario_name_match
    )

    print(
        "Metadata Validation Status: PASS"
    )

    display(
        scenario_metadata
    )

    logger.info(
        "Scenario metadata and uniqueness validation passed."
    )

    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"

    logger.exception(
        "Block 4 failed during metadata validation."
    )

    raise

finally:
    block_end_time = datetime.now()

    block_duration_seconds = round(
        (
            block_end_time
            - block_start_time
        ).total_seconds(),
        3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print(
        "END TIME           :",
        block_end_time.strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )
    print(
        "DURATION (SECONDS) :",
        block_duration_seconds
    )
    print("=" * 80)

================================================================================
MODULE 04: SCENARIO CREATION
BLOCK 4 : METADATA AND UNIQUENESS VALIDATION
START TIME : 2026-10-13 10:30:07
================================================================================
================================================================================
METADATA AND UNIQUENESS VALIDATION
================================================================================
Missing Required Columns: []
Unexpected Columns: []
Duplicate Scenario IDs: 0
Duplicate Scenario Names: 0
Missing Scenario Values: 0
Scenario Names Match SAS V1: True
Metadata Validation Status: PASS

,Column_Name,Python_Data_Type,Non_Missing_Count,Missing_Count,Unique_Values
0,Scenario_ID,int64,3,0,3
1,Scenario_Name,string,3,0,3
2,GDP_Growth,float64,3,0,3
3,Unemployment_Rate,float64,3,0,3
4,Interest_Rate,float64,3,0,3
5,HPI_Change,float64,3,0,3

2026-10-13 10:30:07,866 | INFO | Scenario metadata and uniqueness validation passed.

INFO:04_Scenario_Creation:Scenario metadata and uniqueness validation passed.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 3
OUTPUT RECORDS     : 3
RECORDS PROCESSED  : 3
END TIME           : 2026-10-13 10:30:07
DURATION (SECONDS) : 0.026
================================================================================

In [7]:
# =============================================================================
# BLOCK 5: SCENARIO VARIABLE SUMMARY STATISTICS
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(
    scenario_master
)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 04: SCENARIO CREATION")
print("BLOCK 5 : SCENARIO VARIABLE SUMMARY STATISTICS")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

try:
    scenario_variable_statistics = (
        scenario_master[
            numeric_scenario_columns
        ]
        .agg(
            [
                "count",
                "mean",
                "min",
                "max",
            ]
        )
        .transpose()
        .reset_index()
        .rename(
            columns={
                "index": "Variable",
                "count": "N",
                "mean": "Mean",
                "min": "Minimum",
                "max": "Maximum",
            }
        )
    )

    scenario_variable_statistics[
        "N"
    ] = scenario_variable_statistics[
        "N"
    ].astype("int64")

    for column in [
        "Mean",
        "Minimum",
        "Maximum",
    ]:
        scenario_variable_statistics[column] = (
            scenario_variable_statistics[column]
            .round(2)
        )

    expected_statistics = pd.DataFrame({
        "Variable": [
            "GDP_Growth",
            "Unemployment_Rate",
            "Interest_Rate",
            "HPI_Change",
        ],
        "Expected_N": [
            3,
            3,
            3,
            3,
        ],
        "Expected_Minimum": [
            -2.0,
            5.0,
            6.0,
            -25.0,
        ],
        "Expected_Maximum": [
            6.0,
            10.0,
            11.0,
            0.0,
        ],
    })

    statistics_validation = (
        scenario_variable_statistics
        .merge(
            expected_statistics,
            on="Variable",
            how="left",
            validate="one_to_one"
        )
    )

    statistics_validation[
        "Status"
    ] = np.where(
        (
            statistics_validation["N"]
            == statistics_validation["Expected_N"]
        )
        &
        (
            statistics_validation["Minimum"]
            == statistics_validation["Expected_Minimum"]
        )
        &
        (
            statistics_validation["Maximum"]
            == statistics_validation["Expected_Maximum"]
        ),
        "PASS",
        "FAIL"
    )

    failed_statistics = statistics_validation.loc[
        statistics_validation[
            "Status"
        ] != "PASS"
    ]

    if not failed_statistics.empty:
        raise ValueError(
            "Scenario variable statistics do not match "
            "the SAS V1 assumptions."
        )

    output_record_count = len(
        scenario_variable_statistics
    )

    records_processed = input_record_count

    print("=" * 80)
    print("SCENARIO VARIABLE SUMMARY")
    print("=" * 80)

    display(
        scenario_variable_statistics
    )

    print("\nStatistics Validation:")

    display(
        statistics_validation[
            [
                "Variable",
                "N",
                "Minimum",
                "Maximum",
                "Status",
            ]
        ]
    )

    print(
        "Summary Statistics Validation: PASS"
    )

    logger.info(
        "Scenario summary-statistics validation passed."
    )

    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"

    logger.exception(
        "Block 5 failed during summary-statistics validation."
    )

    raise

finally:
    block_end_time = datetime.now()

    block_duration_seconds = round(
        (
            block_end_time
            - block_start_time
        ).total_seconds(),
        3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print(
        "END TIME           :",
        block_end_time.strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )
    print(
        "DURATION (SECONDS) :",
        block_duration_seconds
    )
    print("=" * 80)

================================================================================
MODULE 04: SCENARIO CREATION
BLOCK 5 : SCENARIO VARIABLE SUMMARY STATISTICS
START TIME : 2026-10-13 10:31:09
================================================================================
================================================================================
SCENARIO VARIABLE SUMMARY
================================================================================

            Variable  N   Mean  Minimum  Maximum
0         GDP_Growth  3   2.33     -2.0      6.0
1  Unemployment_Rate  3   7.33      5.0     10.0
2      Interest_Rate  3   8.33      6.0     11.0
3         HPI_Change  3 -11.67    -25.0      0.0

Statistics Validation:

            Variable  N  Minimum  Maximum Status
0         GDP_Growth  3     -2.0      6.0   PASS
1  Unemployment_Rate  3      5.0     10.0   PASS
2      Interest_Rate  3      6.0     11.0   PASS
3         HPI_Change  3    -25.0      0.0   PASS

Summary Statistics Validation: PASS
2026-10-13 10:31:09,967 | INFO | Scenario summary-statistics validation passed.

INFO:04_Scenario_Creation:Scenario summary-statistics validation passed.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 3
OUTPUT RECORDS     : 4
RECORDS PROCESSED  : 3
END TIME           : 2026-10-13 10:31:09
DURATION (SECONDS) : 0.072
================================================================================

In [10]:
# =============================================================================
# BLOCK 6: FINAL VALIDATION AND RECONCILIATION
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(
    scenario_assumptions
)
output_record_count = len(
    scenario_master
)
records_processed = 0

print("=" * 80)
print("MODULE 04: SCENARIO CREATION")
print("BLOCK 6 : FINAL VALIDATION AND RECONCILIATION")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

try:
    scenario_frequency = (
        scenario_master[
            "Scenario_Name"
        ]
        .value_counts(
            dropna=False
        )
        .reindex(
            expected_scenario_names,
            fill_value=0
        )
        .rename_axis(
            "Scenario_Name"
        )
        .reset_index(
            name="Record_Count"
        )
    )

    scenario_frequency[
        "Expected_Count"
    ] = 1

    scenario_frequency[
        "Status"
    ] = np.where(
        scenario_frequency[
            "Record_Count"
        ]
        ==
        scenario_frequency[
            "Expected_Count"
        ],
        "PASS",
        "FAIL"
    )

    validation_results = pd.DataFrame({
        "Validation_Check": [
            "Scenario Count",
            "Required Column Count",
            "Missing Required Columns",
            "Duplicate Scenario IDs",
            "Duplicate Scenario Names",
            "Missing Scenario Values",
            "Scenario Name and Order Match",
            "Summary Statistics",
        ],
        "Expected_Result": [
            3,
            6,
            0,
            0,
            0,
            0,
            "PASS",
            "PASS",
        ],
        "Actual_Result": [
            len(scenario_master),
            len(scenario_master.columns),
            len(missing_required_columns),
            duplicate_scenario_ids,
            duplicate_scenario_names,
            missing_value_count,
            (
                "PASS"
                if scenario_name_match
                else "FAIL"
            ),
            (
                "PASS"
                if failed_statistics.empty
                else "FAIL"
            ),
        ],
    })

    validation_results[
        "Status"
    ] = np.where(
        validation_results[
            "Expected_Result"
        ].astype(str)
        ==
        validation_results[
            "Actual_Result"
        ].astype(str),
        "PASS",
        "FAIL"
    )

    scenario_creation_summary = pd.DataFrame({
        "Metric": [
            "Scenario Count",
            "Scenario Variable Count",
            "Baseline GDP Growth",
            "Mild Stress GDP Growth",
            "Severe Stress GDP Growth",
            "Maximum Unemployment Rate",
            "Maximum Interest Rate",
            "Minimum HPI Change",
            "Processing Timestamp",
        ],
        "Result": [
            len(scenario_master),
            len(numeric_scenario_columns),
            float(
                scenario_master.loc[
                    scenario_master[
                        "Scenario_Name"
                    ] == "Baseline",
                    "GDP_Growth"
                ].iloc[0]
            ),
            float(
                scenario_master.loc[
                    scenario_master[
                        "Scenario_Name"
                    ] == "Mild_Stress",
                    "GDP_Growth"
                ].iloc[0]
            ),
            float(
                scenario_master.loc[
                    scenario_master[
                        "Scenario_Name"
                    ] == "Severe_Stress",
                    "GDP_Growth"
                ].iloc[0]
            ),
            float(
                scenario_master[
                    "Unemployment_Rate"
                ].max()
            ),
            float(
                scenario_master[
                    "Interest_Rate"
                ].max()
            ),
            float(
                scenario_master[
                    "HPI_Change"
                ].min()
            ),
            datetime.now(),
        ],
    })

    failed_validations = validation_results.loc[
        validation_results[
            "Status"
        ] != "PASS"
    ]

    failed_frequencies = scenario_frequency.loc[
        scenario_frequency[
            "Status"
        ] != "PASS"
    ]

    if not failed_validations.empty:
        raise ValueError(
            "One or more scenario validation checks failed."
        )

    if not failed_frequencies.empty:
        raise ValueError(
            "Scenario frequency validation failed."
        )

    records_processed = output_record_count

    print("=" * 80)
    print("FINAL SCENARIO CREATION VALIDATION")
    print("=" * 80)

    display(
        scenario_frequency
    )

    print("\nValidation Results:")

    display(
        validation_results
    )

    print("\nScenario Creation Summary:")

    display(
        scenario_creation_summary
    )

    print(
        "Overall Module 04 Validation Status: PASS"
    )

    logger.info(
        "All Module 04 validation checks passed."
    )

    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"

    logger.exception(
        "Block 6 failed during final validation."
    )

    raise

finally:
    block_end_time = datetime.now()

    block_duration_seconds = round(
        (
            block_end_time
            - block_start_time
        ).total_seconds(),
        3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print(
        "END TIME           :",
        block_end_time.strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )
    print(
        "DURATION (SECONDS) :",
        block_duration_seconds
    )
    print("=" * 80)

================================================================================
MODULE 04: SCENARIO CREATION
BLOCK 6 : FINAL VALIDATION AND RECONCILIATION
START TIME : 2026-10-13 10:43:54
================================================================================
================================================================================
FINAL SCENARIO CREATION VALIDATION
================================================================================

   Scenario_Name  Record_Count  Expected_Count Status
0       Baseline             1               1   PASS
1    Mild_Stress             1               1   PASS
2  Severe_Stress             1               1   PASS

Validation Results:

                Validation_Check Expected_Result Actual_Result Status
0                 Scenario Count               3             3   PASS
1          Required Column Count               6             6   PASS
2       Missing Required Columns               0             0   PASS
3         Duplicate Scenario IDs               0             0   PASS
4       Duplicate Scenario Names               0             0   PASS
5        Missing Scenario Values               0             0   PASS
6  Scenario Name and Order Match            PASS          PASS   PASS
7             Summary Statistics            PASS          PASS   PASS

Scenario Creation Summary:

                      Metric                      Result
0             Scenario Count                           3
1    Scenario Variable Count                           4
2        Baseline GDP Growth                         6.0
3     Mild Stress GDP Growth                         3.0
4   Severe Stress GDP Growth                        -2.0
5  Maximum Unemployment Rate                        10.0
6      Maximum Interest Rate                        11.0
7         Minimum HPI Change                       -25.0
8       Processing Timestamp  2026-10-13 10:43:54.166104

Overall Module 04 Validation Status: PASS
2026-10-13 10:43:54,202 | INFO | All Module 04 validation checks passed.

INFO:04_Scenario_Creation:All Module 04 validation checks passed.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 3
OUTPUT RECORDS     : 3
RECORDS PROCESSED  : 3
END TIME           : 2026-10-13 10:43:54
DURATION (SECONDS) : 0.051
================================================================================

In [9]:
# =============================================================================
# BLOCK 7: SAVE OUTPUTS, VERIFY FILES, AND CLOSE MODULE
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(
    scenario_master
)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 04: SCENARIO CREATION")
print("BLOCK 7 : SAVE OUTPUTS AND VERIFY FILES")
print(
    "START TIME :",
    block_start_time.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print("=" * 80)

try:
    scenario_master.to_csv(
        OUTPUT_FILE,
        index=False
    )

    scenario_creation_summary.to_csv(
        SUMMARY_FILE,
        index=False
    )

    validation_results.to_csv(
        VALIDATION_FILE,
        index=False
    )

    scenario_variable_statistics.to_csv(
        STATISTICS_FILE,
        index=False
    )

    logger.info(
        "Scenario master and validation evidence "
        "saved successfully."
    )

    expected_output_files = [
        OUTPUT_FILE,
        SUMMARY_FILE,
        VALIDATION_FILE,
        STATISTICS_FILE,
        LOG_FILE,
    ]

    output_verification = pd.DataFrame({
        "File_Name": [
            file_path.name
            for file_path
            in expected_output_files
        ],
        "Exists": [
            file_path.exists()
            for file_path
            in expected_output_files
        ],
        "Size_Bytes": [
            (
                file_path.stat().st_size
                if file_path.exists()
                else 0
            )
            for file_path
            in expected_output_files
        ],
        "Full_Path": [
            str(file_path)
            for file_path
            in expected_output_files
        ],
    })

    if not output_verification[
        "Exists"
    ].all():
        raise FileNotFoundError(
            "One or more Module 04 output files "
            "were not created."
        )

    saved_scenario_master = pd.read_csv(
        OUTPUT_FILE
    )

    output_record_count = len(
        saved_scenario_master
    )

    if output_record_count != expected_scenario_count:
        raise ValueError(
            "Saved scenario-master count does not "
            "equal three."
        )

    records_processed = output_record_count

    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"

    logger.exception(
        "Block 7 failed while saving or verifying outputs."
    )

    raise

finally:
    block_end_time = datetime.now()

    block_duration_seconds = round(
        (
            block_end_time
            - block_start_time
        ).total_seconds(),
        3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print(
        "END TIME           :",
        block_end_time.strftime(
            "%Y-%m-%d %H:%M:%S"
        )
    )
    print(
        "DURATION (SECONDS) :",
        block_duration_seconds
    )
    print("=" * 80)

module_end_timestamp = datetime.now()

module_duration_seconds = round(
    (
        module_end_timestamp
        - module_start_timestamp
    ).total_seconds(),
    3
)

print("=" * 80)
print("PYTHON V2 - MODULE 04 COMPLETED")
print("SCENARIO CREATION EXECUTED SUCCESSFULLY")
print("=" * 80)

print(
    "Scenario Count:",
    output_record_count
)

print(
    "Scenario Output:",
    OUTPUT_FILE
)

print(
    "Validation Summary:",
    SUMMARY_FILE
)

print(
    "Validation Evidence:",
    VALIDATION_FILE
)

print(
    "Variable Statistics:",
    STATISTICS_FILE
)

print(
    "Execution Log:",
    LOG_FILE
)

print("\nOutput File Verification:")

display(
    output_verification
)

print("=" * 80)
print("MODULE STATUS             : SUCCESS")
print(
    "MODULE START              :",
    module_start_timestamp.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "MODULE END                :",
    module_end_timestamp.strftime(
        "%Y-%m-%d %H:%M:%S"
    )
)
print(
    "TOTAL DURATION (SECONDS)  :",
    module_duration_seconds
)
print(
    "TOTAL RECORDS PROCESSED   :",
    output_record_count
)
print("=" * 80)

print(
    "All Module 04 output files verified successfully."
)

logger.info(
    "Module 04 completed successfully in %s seconds.",
    module_duration_seconds
)

================================================================================
MODULE 04: SCENARIO CREATION
BLOCK 7 : SAVE OUTPUTS AND VERIFY FILES
START TIME : 2026-10-13 10:34:52
================================================================================
2026-10-13 10:34:52,957 | INFO | Scenario master and validation evidence saved successfully.

INFO:04_Scenario_Creation:Scenario master and validation evidence saved successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 3
OUTPUT RECORDS     : 3
RECORDS PROCESSED  : 3
END TIME           : 2026-10-13 10:34:52
DURATION (SECONDS) : 0.493
================================================================================
================================================================================
PYTHON V2 - MODULE 04 COMPLETED
SCENARIO CREATION EXECUTED SUCCESSFULLY
================================================================================
Scenario Count: 3
Scenario Output: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/scenario_master.csv
Validation Summary: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/04_scenario_creation_summary.csv
Validation Evidence: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/04_scenario_creation_validation.csv
Variable Statistics: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/04_scenario_variable_statistics.csv
Execution Log: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/04_Scenario_Creation.log

Output File Verification:

,File_Name,Exists,Size_Bytes,Full_Path
0,scenario_master.csv,True,176,/content/drive/MyDrive/Banking_Stress_Testing_...
1,04_scenario_creation_summary.csv,True,269,/content/drive/MyDrive/Banking_Stress_Testing_...
2,04_scenario_creation_validation.csv,True,321,/content/drive/MyDrive/Banking_Stress_Testing_...
3,04_scenario_variable_statistics.csv,True,153,/content/drive/MyDrive/Banking_Stress_Testing_...
4,04_Scenario_Creation.log,True,684,/content/drive/MyDrive/Banking_Stress_Testing_...

================================================================================
MODULE STATUS             : SUCCESS
MODULE START              : 2026-10-13 10:23:38
MODULE END                : 2026-10-13 10:34:52
TOTAL DURATION (SECONDS)  : 674.731
TOTAL RECORDS PROCESSED   : 3
================================================================================
All Module 04 output files verified successfully.
2026-10-13 10:34:52,996 | INFO | Module 04 completed successfully in 674.731 seconds.

INFO:04_Scenario_Creation:Module 04 completed successfully in 674.731 seconds.