In [1]:
# =============================================================================
# 06_PD_STRESS_IMPACT.IPYNB - COPY/PASTE NOTEBOOK CELLS
# Banking Stress Testing Framework - Python V2 Migration
#
# INSTRUCTIONS:
# 1. Create a fresh Colab notebook named 06_PD_Stress_Impact.ipynb.
# 2. Create 9 separate Code cells.
# 3. Copy each CELL section below into its corresponding Colab cell.
# 4. Run strictly from CELL 01 through CELL 09.
# 5. Continue only when the current block ends with BLOCK STATUS : SUCCESS.
# =============================================================================


# =============================================================================
# CELL 01 - MODULE HEADER
# =============================================================================

from datetime import datetime

module_start_timestamp = datetime.now()

print("=" * 80)
print("BANKING STRESS TESTING FRAMEWORK")
print("PYTHON V2 MIGRATION")
print("MODULE : 06_PD_STRESS_IMPACT")
print(
    "EXECUTION STARTED :",
    module_start_timestamp.strftime("%Y-%m-%d %H:%M:%S")
)
print("=" * 80)

================================================================================
BANKING STRESS TESTING FRAMEWORK
PYTHON V2 MIGRATION
MODULE : 06_PD_STRESS_IMPACT
EXECUTION STARTED : 2026-10-13 14:39:12
================================================================================

In [2]:

# =============================================================================
# CELL 02 - BLOCK 1: ENVIRONMENT, PATHS, AND LOGGING
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = 0
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 1 : ENVIRONMENT, PATHS, AND LOGGING")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    from google.colab import drive
    from pathlib import Path
    import logging
    import sys
    import numpy as np
    import pandas as pd

    drive.mount("/content/drive")

    PROJECT_ROOT = Path(
        "/content/drive/MyDrive/Banking_Stress_Testing_V2_Python"
    )

    INPUT_FILE = PROJECT_ROOT / "output" / "portfolio_scenario.csv"
    OUTPUT_FILE = PROJECT_ROOT / "output" / "portfolio_pd.csv"
    VALIDATION_DIR = PROJECT_ROOT / "validation"
    LOG_DIR = PROJECT_ROOT / "logs"

    SUMMARY_FILE = VALIDATION_DIR / "06_pd_stress_summary.csv"
    VALIDATION_FILE = VALIDATION_DIR / "06_pd_stress_validation.csv"
    SCENARIO_SUMMARY_FILE = VALIDATION_DIR / "06_pd_scenario_summary.csv"
    BAND_DISTRIBUTION_FILE = VALIDATION_DIR / "06_pd_band_distribution.csv"
    SAMPLE_FILE = VALIDATION_DIR / "06_pd_stress_sample.csv"
    LOG_FILE = LOG_DIR / "06_PD_Stress_Impact.log"

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    logger = logging.getLogger("06_PD_Stress_Impact")
    logger.setLevel(logging.INFO)

    if logger.hasHandlers():
        logger.handlers.clear()

    log_formatter = logging.Formatter(
        "%(asctime)s | %(levelname)s | %(message)s"
    )

    file_handler = logging.FileHandler(
        LOG_FILE,
        mode="w",
        encoding="utf-8"
    )
    file_handler.setFormatter(log_formatter)

    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(log_formatter)

    logger.addHandler(file_handler)
    logger.addHandler(console_handler)

    if not PROJECT_ROOT.exists():
        raise FileNotFoundError(f"Project root was not found: {PROJECT_ROOT}")

    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Module 05 output was not found: {INPUT_FILE}"
        )

    print("Project Root Exists:", PROJECT_ROOT.exists())
    print("Module 05 Output Exists:", INPUT_FILE.exists())
    print("PD Stress Input:", INPUT_FILE)
    print("PD Stress Output:", OUTPUT_FILE)
    print("Validation Directory:", VALIDATION_DIR)
    print("Execution Log:", LOG_FILE)

    logger.info(
        "Environment, paths, and logging configured successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    if "logger" in locals():
        logger.exception(
            "Block 1 failed during environment configuration."
        )
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 1 : ENVIRONMENT, PATHS, AND LOGGING
START TIME : 2026-10-13 14:42:55
================================================================================
Mounted at /content/drive
Project Root Exists: True
Module 05 Output Exists: True
PD Stress Input: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/portfolio_scenario.csv
PD Stress Output: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/portfolio_pd.csv
Validation Directory: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation
Execution Log: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/06_PD_Stress_Impact.log
2026-10-13 14:43:24,748 | INFO | Environment, paths, and logging configured successfully.

INFO:06_PD_Stress_Impact:Environment, paths, and logging configured successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 0
OUTPUT RECORDS     : 0
RECORDS PROCESSED  : 0
END TIME           : 2026-10-13 14:43:24
DURATION (SECONDS) : 29.542
================================================================================

In [3]:

# =============================================================================
# CELL 03 - BLOCK 2: LOAD AND VALIDATE MODULE 05 OUTPUT
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = 0
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 2 : LOAD AND VALIDATE MODULE 05 OUTPUT")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    required_columns = [
        "Customer_ID",
        "Loan_ID",
        "Risk_Segment",
        "Scenario_ID",
        "Scenario_Name",
        "Outstanding_Balance",
        "GDP_Growth",
        "Unemployment_Rate",
        "Scenario_Interest_Rate",
        "HPI_Change",
    ]

    portfolio_scenario = pd.read_csv(INPUT_FILE, low_memory=False)
    portfolio_pd = portfolio_scenario.copy(deep=True)

    input_record_count = len(portfolio_pd)
    input_column_count = len(portfolio_pd.columns)

    missing_required_columns = sorted(
        set(required_columns) - set(portfolio_pd.columns)
    )

    duplicate_loan_scenario_keys = int(
        portfolio_pd[["Loan_ID", "Scenario_ID"]].duplicated().sum()
    )

    missing_risk_segments = int(
        portfolio_pd["Risk_Segment"].isna().sum()
    )

    missing_scenario_names = int(
        portfolio_pd["Scenario_Name"].isna().sum()
    )

    if missing_required_columns:
        raise ValueError(
            f"Required input columns are missing: {missing_required_columns}"
        )

    if duplicate_loan_scenario_keys > 0:
        raise ValueError(
            "Duplicate Loan_ID and Scenario_ID combinations were found."
        )

    if missing_risk_segments > 0:
        raise ValueError("Missing Risk_Segment values were found.")

    if missing_scenario_names > 0:
        raise ValueError("Missing Scenario_Name values were found.")

    if input_record_count != 30000:
        raise ValueError(
            "Module 05 input does not contain the expected 30,000 records."
        )

    records_processed = input_record_count

    print("=" * 80)
    print("MODULE 05 OUTPUT LOADED SUCCESSFULLY")
    print("=" * 80)
    print("Input Records:", input_record_count)
    print("Input Columns:", input_column_count)
    print("Missing Required Columns:", missing_required_columns)
    print("Duplicate Loan-Scenario Keys:", duplicate_loan_scenario_keys)
    print("Missing Risk Segments:", missing_risk_segments)
    print("Missing Scenario Names:", missing_scenario_names)
    print("Input Validation Status: PASS")

    display(
        portfolio_pd[
            [
                "Customer_ID",
                "Loan_ID",
                "Risk_Segment",
                "Scenario_ID",
                "Scenario_Name",
                "Outstanding_Balance",
            ]
        ].head(15)
    )

    logger.info(
        "Module 05 output loaded successfully: %s records and %s columns.",
        input_record_count,
        input_column_count,
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception("Block 2 failed while loading Module 05 output.")
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 2 : LOAD AND VALIDATE MODULE 05 OUTPUT
START TIME : 2026-10-13 14:46:53
================================================================================
================================================================================
MODULE 05 OUTPUT LOADED SUCCESSFULLY
================================================================================
Input Records: 30000
Input Columns: 30
Missing Required Columns: []
Duplicate Loan-Scenario Keys: 0
Missing Risk Segments: 0
Missing Scenario Names: 0
Input Validation Status: PASS

,Customer_ID,Loan_ID,Risk_Segment,Scenario_ID,Scenario_Name,Outstanding_Balance
0,1000001,50000001,Low Risk,1,Baseline,1733362.19
1,1000001,50000001,Low Risk,2,Mild_Stress,1733362.19
2,1000001,50000001,Low Risk,3,Severe_Stress,1733362.19
3,1000002,50000002,Low Risk,1,Baseline,62244073.93
4,1000002,50000002,Low Risk,2,Mild_Stress,62244073.93
5,1000002,50000002,Low Risk,3,Severe_Stress,62244073.93
6,1000003,50000003,High Risk,1,Baseline,303259.15
7,1000003,50000003,High Risk,2,Mild_Stress,303259.15
8,1000003,50000003,High Risk,3,Severe_Stress,303259.15
9,1000004,50000004,Medium Risk,1,Baseline,993246.23
10,1000004,50000004,Medium Risk,2,Mild_Stress,993246.23
11,1000004,50000004,Medium Risk,3,Severe_Stress,993246.23
12,1000005,50000005,Low Risk,1,Baseline,1654985.49
13,1000005,50000005,Low Risk,2,Mild_Stress,1654985.49
14,1000005,50000005,Low Risk,3,Severe_Stress,1654985.49

2026-10-13 14:46:53,848 | INFO | Module 05 output loaded successfully: 30000 records and 30 columns.

INFO:06_PD_Stress_Impact:Module 05 output loaded successfully: 30000 records and 30 columns.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 0
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 14:46:53
DURATION (SECONDS) : 0.529
================================================================================

In [4]:
# =============================================================================
# CELL 04 - BLOCK 3: ASSIGN BASE PD USING RISK SEGMENT
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_pd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 3 : ASSIGN BASE PD USING RISK SEGMENT")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    base_pd_mapping = {
        "Low Risk": 0.02,
        "Medium Risk": 0.05,
        "High Risk": 0.10,
    }

    portfolio_pd["Base_PD"] = (
        portfolio_pd["Risk_Segment"]
        .map(base_pd_mapping)
        .fillna(0.15)
        .astype("float64")
    )

    base_pd_validation = pd.DataFrame({
        "Risk_Segment": [
            "Low Risk",
            "Medium Risk",
            "High Risk",
            "Other / Unclassified",
        ],
        "Expected_Base_PD": [0.02, 0.05, 0.10, 0.15],
        "Configured_Base_PD": [0.02, 0.05, 0.10, 0.15],
    })

    base_pd_validation["Status"] = np.where(
        np.isclose(
            base_pd_validation["Expected_Base_PD"],
            base_pd_validation["Configured_Base_PD"],
        ),
        "PASS",
        "FAIL",
    )

    missing_base_pd = int(portfolio_pd["Base_PD"].isna().sum())

    invalid_base_pd = int(
        ((portfolio_pd["Base_PD"] <= 0) | (portfolio_pd["Base_PD"] > 1)).sum()
    )

    if missing_base_pd > 0:
        raise ValueError("Missing Base_PD values were created.")

    if invalid_base_pd > 0:
        raise ValueError(
            "Base_PD contains values outside the valid 0-to-1 range."
        )

    output_record_count = len(portfolio_pd)
    records_processed = output_record_count

    base_pd_distribution = (
        portfolio_pd[["Risk_Segment", "Base_PD"]]
        .value_counts(dropna=False)
        .rename("Record_Count")
        .reset_index()
        .sort_values(by=["Base_PD", "Risk_Segment"])
        .reset_index(drop=True)
    )

    print("=" * 80)
    print("BASE PD ASSIGNMENT COMPLETED")
    print("=" * 80)
    display(base_pd_validation)
    print("\nBase PD Distribution:")
    display(base_pd_distribution)
    print("Missing Base PD Values:", missing_base_pd)
    print("Invalid Base PD Values:", invalid_base_pd)
    print("Base PD Validation Status: PASS")

    logger.info("Base PD assignment completed successfully.")
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception("Block 3 failed during Base PD assignment.")
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 3 : ASSIGN BASE PD USING RISK SEGMENT
START TIME : 2026-10-13 14:49:21
================================================================================
================================================================================
BASE PD ASSIGNMENT COMPLETED
================================================================================

           Risk_Segment  Expected_Base_PD  Configured_Base_PD Status
0              Low Risk              0.02                0.02   PASS
1           Medium Risk              0.05                0.05   PASS
2             High Risk              0.10                0.10   PASS
3  Other / Unclassified              0.15                0.15   PASS

Base PD Distribution:

  Risk_Segment  Base_PD  Record_Count
0     Low Risk     0.02          7605
1  Medium Risk     0.05         14940
2    High Risk     0.10          7455

Missing Base PD Values: 0
Invalid Base PD Values: 0
Base PD Validation Status: PASS
2026-10-13 14:49:21,751 | INFO | Base PD assignment completed successfully.

INFO:06_PD_Stress_Impact:Base PD assignment completed successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 14:49:21
DURATION (SECONDS) : 0.032
================================================================================

In [5]:
# =============================================================================
# CELL 05 - BLOCK 4: ASSIGN PD FACTOR USING SCENARIO
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_pd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 4 : ASSIGN PD FACTOR USING SCENARIO")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    pd_factor_mapping = {
        "Baseline": 1.00,
        "Mild_Stress": 1.25,
        "Severe_Stress": 1.75,
    }

    portfolio_pd["PD_Factor"] = (
        portfolio_pd["Scenario_Name"]
        .map(pd_factor_mapping)
        .fillna(1.00)
        .astype("float64")
    )

    pd_factor_validation = pd.DataFrame({
        "Scenario_Name": ["Baseline", "Mild_Stress", "Severe_Stress"],
        "Expected_PD_Factor": [1.00, 1.25, 1.75],
        "Configured_PD_Factor": [1.00, 1.25, 1.75],
    })

    pd_factor_validation["Status"] = np.where(
        np.isclose(
            pd_factor_validation["Expected_PD_Factor"],
            pd_factor_validation["Configured_PD_Factor"],
        ),
        "PASS",
        "FAIL",
    )

    missing_pd_factor = int(portfolio_pd["PD_Factor"].isna().sum())
    invalid_pd_factor = int((portfolio_pd["PD_Factor"] <= 0).sum())

    unexpected_scenarios = sorted(
        set(portfolio_pd["Scenario_Name"].dropna().unique())
        - set(pd_factor_mapping.keys())
    )

    if missing_pd_factor > 0:
        raise ValueError("Missing PD_Factor values were created.")

    if invalid_pd_factor > 0:
        raise ValueError("Invalid non-positive PD factors were created.")

    if unexpected_scenarios:
        raise ValueError(
            f"Unexpected scenarios were found: {unexpected_scenarios}"
        )

    output_record_count = len(portfolio_pd)
    records_processed = output_record_count

    pd_factor_distribution = (
        portfolio_pd[["Scenario_Name", "PD_Factor"]]
        .value_counts(dropna=False)
        .rename("Record_Count")
        .reset_index()
        .sort_values(by="PD_Factor")
        .reset_index(drop=True)
    )

    print("=" * 80)
    print("PD FACTOR ASSIGNMENT COMPLETED")
    print("=" * 80)
    display(pd_factor_validation)
    print("\nScenario PD Factor Distribution:")
    display(pd_factor_distribution)
    print("Missing PD Factors:", missing_pd_factor)
    print("Invalid PD Factors:", invalid_pd_factor)
    print("Unexpected Scenarios:", unexpected_scenarios)
    print("PD Factor Validation Status: PASS")

    logger.info(
        "Scenario PD Factor assignment completed successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception("Block 4 failed during PD Factor assignment.")
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 4 : ASSIGN PD FACTOR USING SCENARIO
START TIME : 2026-10-13 14:51:13
================================================================================
================================================================================
PD FACTOR ASSIGNMENT COMPLETED
================================================================================

   Scenario_Name  Expected_PD_Factor  Configured_PD_Factor Status
0       Baseline                1.00                  1.00   PASS
1    Mild_Stress                1.25                  1.25   PASS
2  Severe_Stress                1.75                  1.75   PASS

Scenario PD Factor Distribution:

   Scenario_Name  PD_Factor  Record_Count
0       Baseline       1.00         10000
1    Mild_Stress       1.25         10000
2  Severe_Stress       1.75         10000

Missing PD Factors: 0
Invalid PD Factors: 0
Unexpected Scenarios: []
PD Factor Validation Status: PASS
2026-10-13 14:51:13,941 | INFO | Scenario PD Factor assignment completed successfully.

INFO:06_PD_Stress_Impact:Scenario PD Factor assignment completed successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 14:51:13
DURATION (SECONDS) : 0.032
================================================================================

In [6]:
# =============================================================================
# CELL 06 - BLOCK 5: CALCULATE STRESSED PD AND ASSIGN PD BAND
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_pd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 5 : CALCULATE STRESSED PD AND PD BAND")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    portfolio_pd["Stressed_PD"] = (
        portfolio_pd["Base_PD"] * portfolio_pd["PD_Factor"]
    )

    pd_band_conditions = [
        portfolio_pd["Stressed_PD"] <= 0.03,
        portfolio_pd["Stressed_PD"] <= 0.08,
    ]

    pd_band_values = ["Low PD", "Medium PD"]

    portfolio_pd["PD_Band"] = np.select(
        pd_band_conditions,
        pd_band_values,
        default="High PD",
    )

    missing_stressed_pd = int(portfolio_pd["Stressed_PD"].isna().sum())

    invalid_stressed_pd = int(
        (
            (portfolio_pd["Stressed_PD"] < 0)
            | (portfolio_pd["Stressed_PD"] > 1)
        ).sum()
    )

    missing_pd_band = int(portfolio_pd["PD_Band"].isna().sum())

    allowed_pd_bands = ["Low PD", "Medium PD", "High PD"]

    invalid_pd_band = int(
        (~portfolio_pd["PD_Band"].isin(allowed_pd_bands)).sum()
    )

    formula_validation_count = int(
        (
            ~np.isclose(
                portfolio_pd["Stressed_PD"],
                portfolio_pd["Base_PD"] * portfolio_pd["PD_Factor"],
            )
        ).sum()
    )

    if missing_stressed_pd > 0:
        raise ValueError("Missing Stressed_PD values were created.")

    if invalid_stressed_pd > 0:
        raise ValueError(
            "Stressed_PD contains values outside the valid 0-to-1 range."
        )

    if missing_pd_band > 0 or invalid_pd_band > 0:
        raise ValueError("Invalid or missing PD Band values were created.")

    if formula_validation_count > 0:
        raise ValueError("Stressed_PD formula validation failed.")

    output_record_count = len(portfolio_pd)
    records_processed = output_record_count

    pd_band_distribution = pd.crosstab(
        portfolio_pd["Scenario_Name"],
        portfolio_pd["PD_Band"],
        margins=True,
        margins_name="Total",
    )

    print("=" * 80)
    print("STRESSED PD AND PD BAND CALCULATION COMPLETED")
    print("=" * 80)
    print("Missing Stressed PD Values:", missing_stressed_pd)
    print("Invalid Stressed PD Values:", invalid_stressed_pd)
    print("Formula Validation Exceptions:", formula_validation_count)
    print("Missing PD Bands:", missing_pd_band)
    print("Invalid PD Bands:", invalid_pd_band)
    print("Stressed PD Formula Validation: PASS")
    print("\nScenario vs PD Band Distribution:")
    display(pd_band_distribution)
    print("\nSample PD Stress Records:")

    display(
        portfolio_pd[
            [
                "Customer_ID",
                "Loan_ID",
                "Risk_Segment",
                "Scenario_Name",
                "Base_PD",
                "PD_Factor",
                "Stressed_PD",
                "PD_Band",
            ]
        ].head(25)
    )

    logger.info(
        "Stressed PD and PD Band calculations completed successfully."
    )
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception("Block 5 failed during Stressed PD calculation.")
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 5 : CALCULATE STRESSED PD AND PD BAND
START TIME : 2026-10-13 14:53:07
================================================================================
================================================================================
STRESSED PD AND PD BAND CALCULATION COMPLETED
================================================================================
Missing Stressed PD Values: 0
Invalid Stressed PD Values: 0
Formula Validation Exceptions: 0
Missing PD Bands: 0
Invalid PD Bands: 0
Stressed PD Formula Validation: PASS

Scenario vs PD Band Distribution:

PD_Band        High PD  Low PD  Medium PD  Total
Scenario_Name
Baseline          2485    2535       4980  10000
Mild_Stress       2485    2535       4980  10000
Severe_Stress     7465       0       2535  10000
Total            12435    5070      12495  30000

Sample PD Stress Records:

,Customer_ID,Loan_ID,Risk_Segment,Scenario_Name,Base_PD,PD_Factor,Stressed_PD,PD_Band
0,1000001,50000001,Low Risk,Baseline,0.02,1.00,0.0200,Low PD
1,1000001,50000001,Low Risk,Mild_Stress,0.02,1.25,0.0250,Low PD
2,1000001,50000001,Low Risk,Severe_Stress,0.02,1.75,0.0350,Medium PD
3,1000002,50000002,Low Risk,Baseline,0.02,1.00,0.0200,Low PD
4,1000002,50000002,Low Risk,Mild_Stress,0.02,1.25,0.0250,Low PD
5,1000002,50000002,Low Risk,Severe_Stress,0.02,1.75,0.0350,Medium PD
6,1000003,50000003,High Risk,Baseline,0.10,1.00,0.1000,High PD
7,1000003,50000003,High Risk,Mild_Stress,0.10,1.25,0.1250,High PD
8,1000003,50000003,High Risk,Severe_Stress,0.10,1.75,0.1750,High PD
9,1000004,50000004,Medium Risk,Baseline,0.05,1.00,0.0500,Medium PD
10,1000004,50000004,Medium Risk,Mild_Stress,0.05,1.25,0.0625,Medium PD
11,1000004,50000004,Medium Risk,Severe_Stress,0.05,1.75,0.0875,High PD
12,1000005,50000005,Low Risk,Baseline,0.02,1.00,0.0200,Low PD
13,1000005,50000005,Low Risk,Mild_Stress,0.02,1.25,0.0250,Low PD
14,1000005,50000005,Low Risk,Severe_Stress,0.02,1.75,0.0350,Medium PD
15,1000006,50000006,Low Risk,Baseline,0.02,1.00,0.0200,Low PD
16,1000006,50000006,Low Risk,Mild_Stress,0.02,1.25,0.0250,Low PD
17,1000006,50000006,Low Risk,Severe_Stress,0.02,1.75,0.0350,Medium PD
18,1000007,50000007,Low Risk,Baseline,0.02,1.00,0.0200,Low PD
19,1000007,50000007,Low Risk,Mild_Stress,0.02,1.25,0.0250,Low PD
20,1000007,50000007,Low Risk,Severe_Stress,0.02,1.75,0.0350,Medium PD
21,1000008,50000008,Medium Risk,Baseline,0.05,1.00,0.0500,Medium PD
22,1000008,50000008,Medium Risk,Mild_Stress,0.05,1.25,0.0625,Medium PD
23,1000008,50000008,Medium Risk,Severe_Stress,0.05,1.75,0.0875,High PD
24,1000009,50000009,Medium Risk,Baseline,0.05,1.00,0.0500,Medium PD

2026-10-13 14:53:07,567 | INFO | Stressed PD and PD Band calculations completed successfully.

INFO:06_PD_Stress_Impact:Stressed PD and PD Band calculations completed successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 14:53:07
DURATION (SECONDS) : 0.084
================================================================================

In [7]:
# =============================================================================
# CELL 07 - BLOCK 6: GENERATE SCENARIO-WISE PD SUMMARY
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_pd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 6 : GENERATE SCENARIO-WISE PD SUMMARY")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    pd_scenario_summary = (
        portfolio_pd.groupby("Scenario_Name", sort=False)
        .agg(
            Record_Count=("Loan_ID", "size"),
            Base_PD_Mean=("Base_PD", "mean"),
            Base_PD_Minimum=("Base_PD", "min"),
            Base_PD_Maximum=("Base_PD", "max"),
            Stressed_PD_Mean=("Stressed_PD", "mean"),
            Stressed_PD_Minimum=("Stressed_PD", "min"),
            Stressed_PD_Maximum=("Stressed_PD", "max"),
        )
        .reset_index()
    )

    numeric_summary_columns = [
        "Base_PD_Mean",
        "Base_PD_Minimum",
        "Base_PD_Maximum",
        "Stressed_PD_Mean",
        "Stressed_PD_Minimum",
        "Stressed_PD_Maximum",
    ]

    pd_scenario_summary[numeric_summary_columns] = (
        pd_scenario_summary[numeric_summary_columns].round(4)
    )

    expected_scenario_counts = {
        "Baseline": 10000,
        "Mild_Stress": 10000,
        "Severe_Stress": 10000,
    }

    pd_scenario_summary["Expected_Record_Count"] = (
        pd_scenario_summary["Scenario_Name"].map(expected_scenario_counts)
    )

    pd_scenario_summary["Status"] = np.where(
        pd_scenario_summary["Record_Count"]
        == pd_scenario_summary["Expected_Record_Count"],
        "PASS",
        "FAIL",
    )

    failed_scenario_summaries = pd_scenario_summary.loc[
        pd_scenario_summary["Status"] != "PASS"
    ]

    if not failed_scenario_summaries.empty:
        raise ValueError("Scenario-wise PD summary validation failed.")

    output_record_count = len(pd_scenario_summary)
    records_processed = input_record_count

    print("=" * 80)
    print("SCENARIO-WISE PD SUMMARY")
    print("=" * 80)
    display(pd_scenario_summary)
    print("Scenario-wise PD Summary Status: PASS")

    logger.info("Scenario-wise PD summary generated successfully.")
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception("Block 6 failed while generating PD summary.")
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 6 : GENERATE SCENARIO-WISE PD SUMMARY
START TIME : 2026-10-13 14:55:41
================================================================================
================================================================================
SCENARIO-WISE PD SUMMARY
================================================================================

,Scenario_Name,Record_Count,Base_PD_Mean,Base_PD_Minimum,Base_PD_Maximum,Stressed_PD_Mean,Stressed_PD_Minimum,Stressed_PD_Maximum,Expected_Record_Count,Status
0,Baseline,10000,0.0548,0.02,0.1,0.0548,0.020,0.100,10000,PASS
1,Mild_Stress,10000,0.0548,0.02,0.1,0.0685,0.025,0.125,10000,PASS
2,Severe_Stress,10000,0.0548,0.02,0.1,0.0959,0.035,0.175,10000,PASS

Scenario-wise PD Summary Status: PASS
2026-10-13 14:55:41,251 | INFO | Scenario-wise PD summary generated successfully.

INFO:06_PD_Stress_Impact:Scenario-wise PD summary generated successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 3
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 14:55:41
DURATION (SECONDS) : 0.032
================================================================================

In [8]:
# =============================================================================
# CELL 08 - BLOCK 7: FINAL VALIDATION AND RECONCILIATION
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_scenario)
output_record_count = len(portfolio_pd)
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 7 : FINAL VALIDATION AND RECONCILIATION")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    final_duplicate_keys = int(
        portfolio_pd[["Loan_ID", "Scenario_ID"]].duplicated().sum()
    )

    final_missing_base_pd = int(portfolio_pd["Base_PD"].isna().sum())
    final_missing_pd_factor = int(portfolio_pd["PD_Factor"].isna().sum())
    final_missing_stressed_pd = int(portfolio_pd["Stressed_PD"].isna().sum())
    final_missing_pd_band = int(portfolio_pd["PD_Band"].isna().sum())

    pd_band_total = int(pd_band_distribution.loc["Total", "Total"])

    validation_results = pd.DataFrame({
        "Validation_Check": [
            "Input and Output Record Count",
            "Expected Output Record Count",
            "Duplicate Loan-Scenario Keys",
            "Missing Base PD",
            "Missing PD Factor",
            "Missing Stressed PD",
            "Missing PD Band",
            "Invalid Base PD",
            "Invalid Stressed PD",
            "Formula Validation Exceptions",
            "PD Band Distribution Total",
        ],
        "Expected_Result": [
            input_record_count,
            30000,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            30000,
        ],
        "Actual_Result": [
            output_record_count,
            output_record_count,
            final_duplicate_keys,
            final_missing_base_pd,
            final_missing_pd_factor,
            final_missing_stressed_pd,
            final_missing_pd_band,
            invalid_base_pd,
            invalid_stressed_pd,
            formula_validation_count,
            pd_band_total,
        ],
    })

    validation_results["Status"] = np.where(
        validation_results["Expected_Result"].astype(str)
        == validation_results["Actual_Result"].astype(str),
        "PASS",
        "FAIL",
    )

    pd_stress_summary = pd.DataFrame({
        "Metric": [
            "Input Records",
            "Output Records",
            "Input Columns",
            "Output Columns",
            "Low Risk Base PD",
            "Medium Risk Base PD",
            "High Risk Base PD",
            "Other Base PD",
            "Baseline PD Factor",
            "Mild Stress PD Factor",
            "Severe Stress PD Factor",
            "Minimum Stressed PD",
            "Maximum Stressed PD",
            "Low PD Band Records",
            "Medium PD Band Records",
            "High PD Band Records",
            "Processing Timestamp",
        ],
        "Result": [
            input_record_count,
            output_record_count,
            input_column_count,
            len(portfolio_pd.columns),
            0.02,
            0.05,
            0.10,
            0.15,
            1.00,
            1.25,
            1.75,
            float(portfolio_pd["Stressed_PD"].min()),
            float(portfolio_pd["Stressed_PD"].max()),
            int((portfolio_pd["PD_Band"] == "Low PD").sum()),
            int((portfolio_pd["PD_Band"] == "Medium PD").sum()),
            int((portfolio_pd["PD_Band"] == "High PD").sum()),
            datetime.now(),
        ],
    })

    failed_validations = validation_results.loc[
        validation_results["Status"] != "PASS"
    ]

    if not failed_validations.empty:
        raise ValueError("One or more Module 06 validation checks failed.")

    records_processed = output_record_count

    print("=" * 80)
    print("FINAL PD STRESS IMPACT VALIDATION")
    print("=" * 80)
    display(validation_results)
    print("\nPD Stress Module Summary:")
    display(pd_stress_summary)
    print("Overall Module 06 Validation Status: PASS")

    logger.info("All Module 06 validation checks passed.")
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception("Block 7 failed during final validation.")
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 7 : FINAL VALIDATION AND RECONCILIATION
START TIME : 2026-10-13 14:57:26
================================================================================
================================================================================
FINAL PD STRESS IMPACT VALIDATION
================================================================================

                 Validation_Check  Expected_Result  Actual_Result Status
0   Input and Output Record Count            30000          30000   PASS
1    Expected Output Record Count            30000          30000   PASS
2    Duplicate Loan-Scenario Keys                0              0   PASS
3                 Missing Base PD                0              0   PASS
4               Missing PD Factor                0              0   PASS
5             Missing Stressed PD                0              0   PASS
6                 Missing PD Band                0              0   PASS
7                 Invalid Base PD                0              0   PASS
8             Invalid Stressed PD                0              0   PASS
9   Formula Validation Exceptions                0              0   PASS
10     PD Band Distribution Total            30000          30000   PASS

PD Stress Module Summary:

                     Metric                      Result
0             Input Records                       30000
1            Output Records                       30000
2             Input Columns                          30
3            Output Columns                          34
4          Low Risk Base PD                        0.02
5       Medium Risk Base PD                        0.05
6         High Risk Base PD                         0.1
7             Other Base PD                        0.15
8        Baseline PD Factor                         1.0
9     Mild Stress PD Factor                        1.25
10  Severe Stress PD Factor                        1.75
11      Minimum Stressed PD                        0.02
12      Maximum Stressed PD                       0.175
13      Low PD Band Records                        5070
14   Medium PD Band Records                       12495
15     High PD Band Records                       12435
16     Processing Timestamp  2026-10-13 14:57:26.736117

Overall Module 06 Validation Status: PASS
2026-10-13 14:57:26,753 | INFO | All Module 06 validation checks passed.

INFO:06_PD_Stress_Impact:All Module 06 validation checks passed.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 14:57:26
DURATION (SECONDS) : 0.033
================================================================================

In [9]:
# =============================================================================
# CELL 09 - BLOCK 8: SAVE OUTPUTS, VERIFY FILES, AND CLOSE MODULE
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_pd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 06: PD STRESS IMPACT")
print("BLOCK 8 : SAVE OUTPUTS AND VERIFY FILES")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    portfolio_pd.to_csv(
        OUTPUT_FILE,
        index=False,
        date_format="%Y-%m-%d"
    )

    pd_stress_summary.to_csv(SUMMARY_FILE, index=False)
    validation_results.to_csv(VALIDATION_FILE, index=False)
    pd_scenario_summary.to_csv(SCENARIO_SUMMARY_FILE, index=False)
    pd_band_distribution.to_csv(BAND_DISTRIBUTION_FILE)

    portfolio_pd.head(25).to_csv(
        SAMPLE_FILE,
        index=False,
        date_format="%Y-%m-%d"
    )

    logger.info(
        "PD-stressed portfolio and validation evidence saved successfully."
    )

    expected_output_files = [
        OUTPUT_FILE,
        SUMMARY_FILE,
        VALIDATION_FILE,
        SCENARIO_SUMMARY_FILE,
        BAND_DISTRIBUTION_FILE,
        SAMPLE_FILE,
        LOG_FILE,
    ]

    output_verification = pd.DataFrame({
        "File_Name": [file_path.name for file_path in expected_output_files],
        "Exists": [file_path.exists() for file_path in expected_output_files],
        "Size_Bytes": [
            file_path.stat().st_size if file_path.exists() else 0
            for file_path in expected_output_files
        ],
        "Full_Path": [str(file_path) for file_path in expected_output_files],
    })

    if not output_verification["Exists"].all():
        raise FileNotFoundError(
            "One or more Module 06 output files were not created."
        )

    saved_output = pd.read_csv(OUTPUT_FILE, low_memory=False)
    output_record_count = len(saved_output)

    if output_record_count != 30000:
        raise ValueError(
            "Saved PD-stressed portfolio does not contain "
            "the expected 30,000 records."
        )

    records_processed = output_record_count
    block_status = "SUCCESS"

except Exception:
    block_status = "FAILED"
    logger.exception("Block 8 failed while saving or verifying outputs.")
    raise

finally:
    block_end_time = datetime.now()
    block_duration_seconds = round(
        (block_end_time - block_start_time).total_seconds(), 3
    )

    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

module_end_timestamp = datetime.now()
module_duration_seconds = round(
    (module_end_timestamp - module_start_timestamp).total_seconds(), 3
)

print("=" * 80)
print("PYTHON V2 - MODULE 06 COMPLETED")
print("PD STRESS IMPACT EXECUTED SUCCESSFULLY")
print("=" * 80)
print("Input Records:", input_record_count)
print("PD-Stressed Records:", output_record_count)
print("PD-Stressed Output:", OUTPUT_FILE)
print("Validation Summary:", SUMMARY_FILE)
print("Validation Evidence:", VALIDATION_FILE)
print("Scenario PD Summary:", SCENARIO_SUMMARY_FILE)
print("PD Band Distribution:", BAND_DISTRIBUTION_FILE)
print("Output Sample:", SAMPLE_FILE)
print("Execution Log:", LOG_FILE)
print("\nOutput File Verification:")
display(output_verification)
print("=" * 80)
print("MODULE STATUS             : SUCCESS")
print(
    "MODULE START              :",
    module_start_timestamp.strftime("%Y-%m-%d %H:%M:%S")
)
print(
    "MODULE END                :",
    module_end_timestamp.strftime("%Y-%m-%d %H:%M:%S")
)
print("TOTAL DURATION (SECONDS)  :", module_duration_seconds)
print("TOTAL RECORDS PROCESSED   :", output_record_count)
print("=" * 80)
print("All Module 06 output files verified successfully.")

logger.info(
    "Module 06 completed successfully in %s seconds.",
    module_duration_seconds
)

================================================================================
MODULE 06: PD STRESS IMPACT
BLOCK 8 : SAVE OUTPUTS AND VERIFY FILES
START TIME : 2026-10-13 15:00:19
================================================================================
2026-10-13 15:00:21,151 | INFO | PD-stressed portfolio and validation evidence saved successfully.

INFO:06_PD_Stress_Impact:PD-stressed portfolio and validation evidence saved successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:00:21
DURATION (SECONDS) : 1.342
================================================================================
================================================================================
PYTHON V2 - MODULE 06 COMPLETED
PD STRESS IMPACT EXECUTED SUCCESSFULLY
================================================================================
Input Records: 30000
PD-Stressed Records: 30000
PD-Stressed Output: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/portfolio_pd.csv
Validation Summary: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/06_pd_stress_summary.csv
Validation Evidence: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/06_pd_stress_validation.csv
Scenario PD Summary: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/06_pd_scenario_summary.csv
PD Band Distribution: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/06_pd_band_distribution.csv
Output Sample: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/06_pd_stress_sample.csv
Execution Log: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/06_PD_Stress_Impact.log

Output File Verification:

,File_Name,Exists,Size_Bytes,Full_Path
0,portfolio_pd.csv,True,7072962,/content/drive/MyDrive/Banking_Stress_Testing_...
1,06_pd_stress_summary.csv,True,451,/content/drive/MyDrive/Banking_Stress_Testing_...
2,06_pd_stress_validation.csv,True,428,/content/drive/MyDrive/Banking_Stress_Testing_...
3,06_pd_scenario_summary.csv,True,346,/content/drive/MyDrive/Banking_Stress_Testing_...
4,06_pd_band_distribution.csv,True,169,/content/drive/MyDrive/Banking_Stress_Testing_...
5,06_pd_stress_sample.csv,True,6293,/content/drive/MyDrive/Banking_Stress_Testing_...
6,06_PD_Stress_Impact.log,True,702,/content/drive/MyDrive/Banking_Stress_Testing_...

================================================================================
MODULE STATUS             : SUCCESS
MODULE START              : 2026-10-13 14:39:12
MODULE END                : 2026-10-13 15:00:21
TOTAL DURATION (SECONDS)  : 1268.332
TOTAL RECORDS PROCESSED   : 30000
================================================================================
All Module 06 output files verified successfully.
2026-10-13 15:00:21,311 | INFO | Module 06 completed successfully in 1268.332 seconds.

INFO:06_PD_Stress_Impact:Module 06 completed successfully in 1268.332 seconds.