In [1]:
# =============================================================================
# 07_LGD_STRESS_IMPACT.IPYNB - COPY/PASTE NOTEBOOK CELLS
# Banking Stress Testing Framework - Python V2 Migration
#
# SAS V1 GOLDEN-REFERENCE RULES
# Base LGD by Product:
# Mortgage 0.20 | Auto Loan 0.35 | SME Loan 0.40 | Corporate Loan 0.45
# Personal Loan 0.60 | Credit Card 0.85 | Other 0.50
# Scenario Factor:
# Baseline 1.00 | Mild_Stress 1.10 | Severe_Stress 1.25 | Other 1.00
# Stressed_LGD = min(Base_LGD * LGD_Factor, 1.00)
# LGD Band: <0.30 Low LGD | <=0.60 Medium LGD | otherwise High LGD
#
# INSTRUCTIONS
# 1. Create 07_LGD_Stress_Impact.ipynb in Colab.
# 2. Create nine separate Code cells.
# 3. Copy each CELL section into the matching Colab cell.
# 4. Run CELL 01 through CELL 09 strictly in sequence.
# 5. Continue only after BLOCK STATUS : SUCCESS.
# =============================================================================

# =============================================================================
# CELL 01 - MODULE HEADER
# =============================================================================

from datetime import datetime

module_start_timestamp = datetime.now()

print("=" * 80)
print("BANKING STRESS TESTING FRAMEWORK")
print("PYTHON V2 MIGRATION")
print("MODULE : 07_LGD_STRESS_IMPACT")
print("EXECUTION STARTED :", module_start_timestamp.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

================================================================================
BANKING STRESS TESTING FRAMEWORK
PYTHON V2 MIGRATION
MODULE : 07_LGD_STRESS_IMPACT
EXECUTION STARTED : 2026-10-13 15:14:35
================================================================================

In [2]:
# =============================================================================
# 07_LGD_STRESS_IMPACT.IPYNB - COPY/PASTE NOTEBOOK CELLS
# Banking Stress Testing Framework - Python V2 Migration
#
# SAS V1 GOLDEN-REFERENCE RULES
# Base LGD by Product:
# Mortgage 0.20 | Auto Loan 0.35 | SME Loan 0.40 | Corporate Loan 0.45
# Personal Loan 0.60 | Credit Card 0.85 | Other 0.50
# Scenario Factor:
# Baseline 1.00 | Mild_Stress 1.10 | Severe_Stress 1.25 | Other 1.00
# Stressed_LGD = min(Base_LGD * LGD_Factor, 1.00)
# LGD Band: <0.30 Low LGD | <=0.60 Medium LGD | otherwise High LGD
#
# INSTRUCTIONS
# 1. Create 07_LGD_Stress_Impact.ipynb in Colab.
# 2. Create nine separate Code cells.
# 3. Copy each CELL section into the matching Colab cell.
# 4. Run CELL 01 through CELL 09 strictly in sequence.
# 5. Continue only after BLOCK STATUS : SUCCESS.
# =============================================================================

# =============================================================================
# CELL 01 - MODULE HEADER
# =============================================================================

from datetime import datetime

module_start_timestamp = datetime.now()

print("=" * 80)
print("BANKING STRESS TESTING FRAMEWORK")
print("PYTHON V2 MIGRATION")
print("MODULE : 07_LGD_STRESS_IMPACT")
print("EXECUTION STARTED :", module_start_timestamp.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)


# =============================================================================
# CELL 02 - BLOCK 1: ENVIRONMENT, PATHS, AND LOGGING
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = 0
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 1 : ENVIRONMENT, PATHS, AND LOGGING")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    from google.colab import drive
    from pathlib import Path
    import logging
    import sys
    import numpy as np
    import pandas as pd

    drive.mount("/content/drive")

    PROJECT_ROOT = Path("/content/drive/MyDrive/Banking_Stress_Testing_V2_Python")
    INPUT_FILE = PROJECT_ROOT / "output" / "portfolio_pd.csv"
    OUTPUT_FILE = PROJECT_ROOT / "output" / "portfolio_lgd.csv"
    VALIDATION_DIR = PROJECT_ROOT / "validation"
    LOG_DIR = PROJECT_ROOT / "logs"

    SUMMARY_FILE = VALIDATION_DIR / "07_lgd_stress_summary.csv"
    VALIDATION_FILE = VALIDATION_DIR / "07_lgd_stress_validation.csv"
    SCENARIO_SUMMARY_FILE = VALIDATION_DIR / "07_lgd_scenario_summary.csv"
    BAND_DISTRIBUTION_FILE = VALIDATION_DIR / "07_lgd_band_distribution.csv"
    PRODUCT_DISTRIBUTION_FILE = VALIDATION_DIR / "07_lgd_product_distribution.csv"
    SAMPLE_FILE = VALIDATION_DIR / "07_lgd_stress_sample.csv"
    LOG_FILE = LOG_DIR / "07_LGD_Stress_Impact.log"

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    VALIDATION_DIR.mkdir(parents=True, exist_ok=True)
    LOG_DIR.mkdir(parents=True, exist_ok=True)

    logger = logging.getLogger("07_LGD_Stress_Impact")
    logger.setLevel(logging.INFO)
    if logger.hasHandlers():
        logger.handlers.clear()

    log_formatter = logging.Formatter("%(asctime)s | %(levelname)s | %(message)s")
    file_handler = logging.FileHandler(LOG_FILE, mode="w", encoding="utf-8")
    file_handler.setFormatter(log_formatter)
    console_handler = logging.StreamHandler(sys.stdout)
    console_handler.setFormatter(log_formatter)
    logger.addHandler(file_handler)
    logger.addHandler(console_handler)

    if not PROJECT_ROOT.exists():
        raise FileNotFoundError(f"Project root was not found: {PROJECT_ROOT}")
    if not INPUT_FILE.exists():
        raise FileNotFoundError(f"Module 06 output was not found: {INPUT_FILE}")

    print("Project Root Exists:", PROJECT_ROOT.exists())
    print("Module 06 Output Exists:", INPUT_FILE.exists())
    print("LGD Stress Input:", INPUT_FILE)
    print("LGD Stress Output:", OUTPUT_FILE)
    print("Validation Directory:", VALIDATION_DIR)
    print("Execution Log:", LOG_FILE)

    logger.info("Environment, paths, and logging configured successfully.")
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    if "logger" in locals():
        logger.exception("Block 1 failed during environment configuration.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
BANKING STRESS TESTING FRAMEWORK
PYTHON V2 MIGRATION
MODULE : 07_LGD_STRESS_IMPACT
EXECUTION STARTED : 2026-10-13 15:17:36
================================================================================
================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 1 : ENVIRONMENT, PATHS, AND LOGGING
START TIME : 2026-10-13 15:17:36
================================================================================
Mounted at /content/drive
Project Root Exists: True
Module 06 Output Exists: True
LGD Stress Input: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/portfolio_pd.csv
LGD Stress Output: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/portfolio_lgd.csv
Validation Directory: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation
Execution Log: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/07_LGD_Stress_Impact.log
2026-10-13 15:18:06,489 | INFO | Environment, paths, and logging configured successfully.

INFO:07_LGD_Stress_Impact:Environment, paths, and logging configured successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 0
OUTPUT RECORDS     : 0
RECORDS PROCESSED  : 0
END TIME           : 2026-10-13 15:18:06
DURATION (SECONDS) : 30.129
================================================================================

In [3]:
# =============================================================================
# CELL 03 - BLOCK 2: LOAD AND VALIDATE MODULE 06 OUTPUT
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = 0
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 2 : LOAD AND VALIDATE MODULE 06 OUTPUT")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    required_columns = [
        "Customer_ID", "Loan_ID", "Product_Type", "Scenario_ID",
        "Scenario_Name", "Outstanding_Balance", "Base_PD", "PD_Factor",
        "Stressed_PD", "PD_Band"
    ]

    portfolio_pd = pd.read_csv(INPUT_FILE, low_memory=False)
    portfolio_lgd = portfolio_pd.copy(deep=True)

    input_record_count = len(portfolio_lgd)
    input_column_count = len(portfolio_lgd.columns)
    missing_required_columns = sorted(set(required_columns) - set(portfolio_lgd.columns))
    duplicate_loan_scenario_keys = int(
        portfolio_lgd[["Loan_ID", "Scenario_ID"]].duplicated().sum()
    )
    missing_product_types = int(portfolio_lgd["Product_Type"].isna().sum())
    missing_scenario_names = int(portfolio_lgd["Scenario_Name"].isna().sum())

    if missing_required_columns:
        raise ValueError(f"Required input columns are missing: {missing_required_columns}")
    if duplicate_loan_scenario_keys > 0:
        raise ValueError("Duplicate Loan_ID and Scenario_ID combinations were found.")
    if missing_product_types > 0:
        raise ValueError("Missing Product_Type values were found.")
    if missing_scenario_names > 0:
        raise ValueError("Missing Scenario_Name values were found.")
    if input_record_count != 30000:
        raise ValueError("Module 06 input does not contain the expected 30,000 records.")

    records_processed = input_record_count

    print("=" * 80)
    print("MODULE 06 OUTPUT LOADED SUCCESSFULLY")
    print("=" * 80)
    print("Input Records:", input_record_count)
    print("Input Columns:", input_column_count)
    print("Missing Required Columns:", missing_required_columns)
    print("Duplicate Loan-Scenario Keys:", duplicate_loan_scenario_keys)
    print("Missing Product Types:", missing_product_types)
    print("Missing Scenario Names:", missing_scenario_names)
    print("Input Validation Status: PASS")

    display(portfolio_lgd[[
        "Customer_ID", "Loan_ID", "Product_Type", "Scenario_ID",
        "Scenario_Name", "Stressed_PD", "PD_Band"
    ]].head(15))

    logger.info(
        "Module 06 output loaded successfully: %s records and %s columns.",
        input_record_count, input_column_count
    )
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    logger.exception("Block 2 failed while loading Module 06 output.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 2 : LOAD AND VALIDATE MODULE 06 OUTPUT
START TIME : 2026-10-13 15:19:33
================================================================================
================================================================================
MODULE 06 OUTPUT LOADED SUCCESSFULLY
================================================================================
Input Records: 30000
Input Columns: 34
Missing Required Columns: []
Duplicate Loan-Scenario Keys: 0
Missing Product Types: 0
Missing Scenario Names: 0
Input Validation Status: PASS

,Customer_ID,Loan_ID,Product_Type,Scenario_ID,Scenario_Name,Stressed_PD,PD_Band
0,1000001,50000001,Personal Loan,1,Baseline,0.0200,Low PD
1,1000001,50000001,Personal Loan,2,Mild_Stress,0.0250,Low PD
2,1000001,50000001,Personal Loan,3,Severe_Stress,0.0350,Medium PD
3,1000002,50000002,Corporate Loan,1,Baseline,0.0200,Low PD
4,1000002,50000002,Corporate Loan,2,Mild_Stress,0.0250,Low PD
5,1000002,50000002,Corporate Loan,3,Severe_Stress,0.0350,Medium PD
6,1000003,50000003,Credit Card,1,Baseline,0.1000,High PD
7,1000003,50000003,Credit Card,2,Mild_Stress,0.1250,High PD
8,1000003,50000003,Credit Card,3,Severe_Stress,0.1750,High PD
9,1000004,50000004,Auto Loan,1,Baseline,0.0500,Medium PD
10,1000004,50000004,Auto Loan,2,Mild_Stress,0.0625,Medium PD
11,1000004,50000004,Auto Loan,3,Severe_Stress,0.0875,High PD
12,1000005,50000005,Personal Loan,1,Baseline,0.0200,Low PD
13,1000005,50000005,Personal Loan,2,Mild_Stress,0.0250,Low PD
14,1000005,50000005,Personal Loan,3,Severe_Stress,0.0350,Medium PD

2026-10-13 15:19:34,203 | INFO | Module 06 output loaded successfully: 30000 records and 34 columns.

INFO:07_LGD_Stress_Impact:Module 06 output loaded successfully: 30000 records and 34 columns.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 0
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:19:34
DURATION (SECONDS) : 1.103
================================================================================

In [4]:
# =============================================================================
# CELL 04 - BLOCK 3: ASSIGN BASE LGD USING PRODUCT TYPE
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_lgd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 3 : ASSIGN BASE LGD USING PRODUCT TYPE")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    base_lgd_mapping = {
        "Mortgage": 0.20,
        "Auto Loan": 0.35,
        "SME Loan": 0.40,
        "Corporate Loan": 0.45,
        "Personal Loan": 0.60,
        "Credit Card": 0.85,
    }
    fallback_base_lgd = 0.50

    portfolio_lgd["Base_LGD"] = (
        portfolio_lgd["Product_Type"]
        .map(base_lgd_mapping)
        .fillna(fallback_base_lgd)
        .astype("float64")
    )

    base_lgd_validation = pd.DataFrame({
        "Product_Type": [
            "Mortgage", "Auto Loan", "SME Loan", "Corporate Loan",
            "Personal Loan", "Credit Card", "Other / Unclassified"
        ],
        "Expected_Base_LGD": [0.20, 0.35, 0.40, 0.45, 0.60, 0.85, 0.50],
        "Configured_Base_LGD": [
            base_lgd_mapping["Mortgage"], base_lgd_mapping["Auto Loan"],
            base_lgd_mapping["SME Loan"], base_lgd_mapping["Corporate Loan"],
            base_lgd_mapping["Personal Loan"], base_lgd_mapping["Credit Card"],
            fallback_base_lgd
        ],
    })
    base_lgd_validation["Status"] = np.where(
        np.isclose(
            base_lgd_validation["Expected_Base_LGD"],
            base_lgd_validation["Configured_Base_LGD"]
        ),
        "PASS", "FAIL"
    )

    missing_base_lgd = int(portfolio_lgd["Base_LGD"].isna().sum())
    invalid_base_lgd = int(
        ((portfolio_lgd["Base_LGD"] < 0) | (portfolio_lgd["Base_LGD"] > 1)).sum()
    )
    unexpected_product_types = sorted(
        set(portfolio_lgd["Product_Type"].dropna().unique())
        - set(base_lgd_mapping.keys())
    )

    if missing_base_lgd > 0:
        raise ValueError("Missing Base_LGD values were created.")
    if invalid_base_lgd > 0:
        raise ValueError("Base_LGD contains values outside the valid 0-to-1 range.")

    output_record_count = len(portfolio_lgd)
    records_processed = output_record_count

    base_lgd_distribution = (
        portfolio_lgd[["Product_Type", "Base_LGD"]]
        .value_counts(dropna=False)
        .rename("Record_Count")
        .reset_index()
        .sort_values(by=["Base_LGD", "Product_Type"])
        .reset_index(drop=True)
    )

    print("=" * 80)
    print("BASE LGD ASSIGNMENT COMPLETED")
    print("=" * 80)
    display(base_lgd_validation)
    print("\nBase LGD Distribution:")
    display(base_lgd_distribution)
    print("Missing Base LGD Values:", missing_base_lgd)
    print("Invalid Base LGD Values:", invalid_base_lgd)
    print("Unexpected Product Types Using Fallback:", unexpected_product_types)
    print("Base LGD Validation Status: PASS")

    logger.info("Base LGD assignment completed successfully.")
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    logger.exception("Block 3 failed during Base LGD assignment.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 3 : ASSIGN BASE LGD USING PRODUCT TYPE
START TIME : 2026-10-13 15:21:50
================================================================================
================================================================================
BASE LGD ASSIGNMENT COMPLETED
================================================================================

           Product_Type  Expected_Base_LGD  Configured_Base_LGD Status
0              Mortgage               0.20                 0.20   PASS
1             Auto Loan               0.35                 0.35   PASS
2              SME Loan               0.40                 0.40   PASS
3        Corporate Loan               0.45                 0.45   PASS
4         Personal Loan               0.60                 0.60   PASS
5           Credit Card               0.85                 0.85   PASS
6  Other / Unclassified               0.50                 0.50   PASS

Base LGD Distribution:

     Product_Type  Base_LGD  Record_Count
0        Mortgage      0.20          7650
1       Auto Loan      0.35          6264
2        SME Loan      0.40          3855
3  Corporate Loan      0.45          1215
4   Personal Loan      0.60          6351
5     Credit Card      0.85          4665

Missing Base LGD Values: 0
Invalid Base LGD Values: 0
Unexpected Product Types Using Fallback: []
Base LGD Validation Status: PASS
2026-10-13 15:21:51,006 | INFO | Base LGD assignment completed successfully.

INFO:07_LGD_Stress_Impact:Base LGD assignment completed successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:21:51
DURATION (SECONDS) : 0.079
================================================================================

In [5]:
# =============================================================================
# CELL 05 - BLOCK 4: ASSIGN LGD FACTOR USING SCENARIO
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_lgd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 4 : ASSIGN LGD FACTOR USING SCENARIO")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    lgd_factor_mapping = {
        "Baseline": 1.00,
        "Mild_Stress": 1.10,
        "Severe_Stress": 1.25,
    }
    fallback_lgd_factor = 1.00

    portfolio_lgd["LGD_Factor"] = (
        portfolio_lgd["Scenario_Name"]
        .map(lgd_factor_mapping)
        .fillna(fallback_lgd_factor)
        .astype("float64")
    )

    lgd_factor_validation = pd.DataFrame({
        "Scenario_Name": ["Baseline", "Mild_Stress", "Severe_Stress", "Other"],
        "Expected_LGD_Factor": [1.00, 1.10, 1.25, 1.00],
        "Configured_LGD_Factor": [1.00, 1.10, 1.25, fallback_lgd_factor],
    })
    lgd_factor_validation["Status"] = np.where(
        np.isclose(
            lgd_factor_validation["Expected_LGD_Factor"],
            lgd_factor_validation["Configured_LGD_Factor"]
        ),
        "PASS", "FAIL"
    )

    missing_lgd_factor = int(portfolio_lgd["LGD_Factor"].isna().sum())
    invalid_lgd_factor = int((portfolio_lgd["LGD_Factor"] <= 0).sum())
    unexpected_scenarios = sorted(
        set(portfolio_lgd["Scenario_Name"].dropna().unique())
        - set(lgd_factor_mapping.keys())
    )

    if missing_lgd_factor > 0:
        raise ValueError("Missing LGD_Factor values were created.")
    if invalid_lgd_factor > 0:
        raise ValueError("Invalid non-positive LGD factors were created.")
    if unexpected_scenarios:
        raise ValueError(f"Unexpected scenarios were found: {unexpected_scenarios}")

    output_record_count = len(portfolio_lgd)
    records_processed = output_record_count

    lgd_factor_distribution = (
        portfolio_lgd[["Scenario_Name", "LGD_Factor"]]
        .value_counts(dropna=False)
        .rename("Record_Count")
        .reset_index()
        .sort_values(by="LGD_Factor")
        .reset_index(drop=True)
    )

    print("=" * 80)
    print("LGD FACTOR ASSIGNMENT COMPLETED")
    print("=" * 80)
    display(lgd_factor_validation)
    print("\nScenario LGD Factor Distribution:")
    display(lgd_factor_distribution)
    print("Missing LGD Factors:", missing_lgd_factor)
    print("Invalid LGD Factors:", invalid_lgd_factor)
    print("Unexpected Scenarios:", unexpected_scenarios)
    print("LGD Factor Validation Status: PASS")

    logger.info("Scenario LGD Factor assignment completed successfully.")
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    logger.exception("Block 4 failed during LGD Factor assignment.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 4 : ASSIGN LGD FACTOR USING SCENARIO
START TIME : 2026-10-13 15:23:37
================================================================================
================================================================================
LGD FACTOR ASSIGNMENT COMPLETED
================================================================================

   Scenario_Name  Expected_LGD_Factor  Configured_LGD_Factor Status
0       Baseline                 1.00                   1.00   PASS
1    Mild_Stress                 1.10                   1.10   PASS
2  Severe_Stress                 1.25                   1.25   PASS
3          Other                 1.00                   1.00   PASS

Scenario LGD Factor Distribution:

   Scenario_Name  LGD_Factor  Record_Count
0       Baseline        1.00         10000
1    Mild_Stress        1.10         10000
2  Severe_Stress        1.25         10000

Missing LGD Factors: 0
Invalid LGD Factors: 0
Unexpected Scenarios: []
LGD Factor Validation Status: PASS
2026-10-13 15:23:37,828 | INFO | Scenario LGD Factor assignment completed successfully.

INFO:07_LGD_Stress_Impact:Scenario LGD Factor assignment completed successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:23:37
DURATION (SECONDS) : 0.05
================================================================================

In [6]:
# =============================================================================
# CELL 06 - BLOCK 5: CALCULATE STRESSED LGD AND ASSIGN LGD BAND
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_lgd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 5 : CALCULATE STRESSED LGD AND LGD BAND")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    uncapped_stressed_lgd = portfolio_lgd["Base_LGD"] * portfolio_lgd["LGD_Factor"]
    portfolio_lgd["Stressed_LGD"] = uncapped_stressed_lgd.clip(upper=1.00)
    capped_lgd_records = int((uncapped_stressed_lgd > 1.00).sum())

    lgd_band_conditions = [
        portfolio_lgd["Stressed_LGD"] < 0.30,
        portfolio_lgd["Stressed_LGD"] <= 0.60,
    ]
    portfolio_lgd["LGD_Band"] = np.select(
        lgd_band_conditions,
        ["Low LGD", "Medium LGD"],
        default="High LGD"
    )

    missing_stressed_lgd = int(portfolio_lgd["Stressed_LGD"].isna().sum())
    invalid_stressed_lgd = int(
        ((portfolio_lgd["Stressed_LGD"] < 0) | (portfolio_lgd["Stressed_LGD"] > 1)).sum()
    )
    formula_validation_exceptions = int(
        (~np.isclose(
            portfolio_lgd["Stressed_LGD"],
            np.minimum(uncapped_stressed_lgd, 1.00)
        )).sum()
    )
    allowed_lgd_bands = ["Low LGD", "Medium LGD", "High LGD"]
    missing_lgd_band = int(portfolio_lgd["LGD_Band"].isna().sum())
    invalid_lgd_band = int((~portfolio_lgd["LGD_Band"].isin(allowed_lgd_bands)).sum())

    if missing_stressed_lgd > 0:
        raise ValueError("Missing Stressed_LGD values were created.")
    if invalid_stressed_lgd > 0:
        raise ValueError("Stressed_LGD contains values outside the 0-to-1 range.")
    if formula_validation_exceptions > 0:
        raise ValueError("Stressed_LGD formula or cap validation failed.")
    if missing_lgd_band > 0 or invalid_lgd_band > 0:
        raise ValueError("Invalid or missing LGD Band values were created.")

    output_record_count = len(portfolio_lgd)
    records_processed = output_record_count

    lgd_band_distribution = pd.crosstab(
        portfolio_lgd["Scenario_Name"],
        portfolio_lgd["LGD_Band"],
        margins=True,
        margins_name="Total"
    )

    print("=" * 80)
    print("STRESSED LGD AND LGD BAND CALCULATION COMPLETED")
    print("=" * 80)
    print("Missing Stressed LGD Values:", missing_stressed_lgd)
    print("Invalid Stressed LGD Values:", invalid_stressed_lgd)
    print("LGD Records Capped at 100%:", capped_lgd_records)
    print("Formula / Cap Validation Exceptions:", formula_validation_exceptions)
    print("Missing LGD Bands:", missing_lgd_band)
    print("Invalid LGD Bands:", invalid_lgd_band)
    print("Stressed LGD Formula Validation: PASS")
    print("\nScenario vs LGD Band Distribution:")
    display(lgd_band_distribution)
    print("\nSample LGD Stress Records:")
    display(portfolio_lgd[[
        "Customer_ID", "Loan_ID", "Product_Type", "Scenario_Name",
        "Base_LGD", "LGD_Factor", "Stressed_LGD", "LGD_Band"
    ]].head(25))

    logger.info("Stressed LGD and LGD Band calculations completed successfully.")
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    logger.exception("Block 5 failed during Stressed LGD calculation.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 5 : CALCULATE STRESSED LGD AND LGD BAND
START TIME : 2026-10-13 15:24:58
================================================================================
================================================================================
STRESSED LGD AND LGD BAND CALCULATION COMPLETED
================================================================================
Missing Stressed LGD Values: 0
Invalid Stressed LGD Values: 0
LGD Records Capped at 100%: 1555
Formula / Cap Validation Exceptions: 0
Missing LGD Bands: 0
Invalid LGD Bands: 0
Stressed LGD Formula Validation: PASS

Scenario vs LGD Band Distribution:

LGD_Band       High LGD  Low LGD  Medium LGD  Total
Scenario_Name
Baseline           1555     2550        5895  10000
Mild_Stress        3672     2550        3778  10000
Severe_Stress      3672     2550        3778  10000
Total              8899     7650       13451  30000

Sample LGD Stress Records:

,Customer_ID,Loan_ID,Product_Type,Scenario_Name,Base_LGD,LGD_Factor,Stressed_LGD,LGD_Band
0,1000001,50000001,Personal Loan,Baseline,0.60,1.00,0.6000,Medium LGD
1,1000001,50000001,Personal Loan,Mild_Stress,0.60,1.10,0.6600,High LGD
2,1000001,50000001,Personal Loan,Severe_Stress,0.60,1.25,0.7500,High LGD
3,1000002,50000002,Corporate Loan,Baseline,0.45,1.00,0.4500,Medium LGD
4,1000002,50000002,Corporate Loan,Mild_Stress,0.45,1.10,0.4950,Medium LGD
5,1000002,50000002,Corporate Loan,Severe_Stress,0.45,1.25,0.5625,Medium LGD
6,1000003,50000003,Credit Card,Baseline,0.85,1.00,0.8500,High LGD
7,1000003,50000003,Credit Card,Mild_Stress,0.85,1.10,0.9350,High LGD
8,1000003,50000003,Credit Card,Severe_Stress,0.85,1.25,1.0000,High LGD
9,1000004,50000004,Auto Loan,Baseline,0.35,1.00,0.3500,Medium LGD
10,1000004,50000004,Auto Loan,Mild_Stress,0.35,1.10,0.3850,Medium LGD
11,1000004,50000004,Auto Loan,Severe_Stress,0.35,1.25,0.4375,Medium LGD
12,1000005,50000005,Personal Loan,Baseline,0.60,1.00,0.6000,Medium LGD
13,1000005,50000005,Personal Loan,Mild_Stress,0.60,1.10,0.6600,High LGD
14,1000005,50000005,Personal Loan,Severe_Stress,0.60,1.25,0.7500,High LGD
15,1000006,50000006,Credit Card,Baseline,0.85,1.00,0.8500,High LGD
16,1000006,50000006,Credit Card,Mild_Stress,0.85,1.10,0.9350,High LGD
17,1000006,50000006,Credit Card,Severe_Stress,0.85,1.25,1.0000,High LGD
18,1000007,50000007,Auto Loan,Baseline,0.35,1.00,0.3500,Medium LGD
19,1000007,50000007,Auto Loan,Mild_Stress,0.35,1.10,0.3850,Medium LGD
20,1000007,50000007,Auto Loan,Severe_Stress,0.35,1.25,0.4375,Medium LGD
21,1000008,50000008,SME Loan,Baseline,0.40,1.00,0.4000,Medium LGD
22,1000008,50000008,SME Loan,Mild_Stress,0.40,1.10,0.4400,Medium LGD
23,1000008,50000008,SME Loan,Severe_Stress,0.40,1.25,0.5000,Medium LGD
24,1000009,50000009,Credit Card,Baseline,0.85,1.00,0.8500,High LGD

2026-10-13 15:24:58,506 | INFO | Stressed LGD and LGD Band calculations completed successfully.

INFO:07_LGD_Stress_Impact:Stressed LGD and LGD Band calculations completed successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:24:58
DURATION (SECONDS) : 0.127
================================================================================

In [7]:
# =============================================================================
# CELL 07 - BLOCK 6: GENERATE SCENARIO-WISE LGD SUMMARY
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_lgd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 6 : GENERATE SCENARIO-WISE LGD SUMMARY")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    lgd_scenario_summary = (
        portfolio_lgd.groupby("Scenario_Name", sort=False)
        .agg(
            Record_Count=("Loan_ID", "size"),
            Base_LGD_Mean=("Base_LGD", "mean"),
            Base_LGD_Minimum=("Base_LGD", "min"),
            Base_LGD_Maximum=("Base_LGD", "max"),
            Stressed_LGD_Mean=("Stressed_LGD", "mean"),
            Stressed_LGD_Minimum=("Stressed_LGD", "min"),
            Stressed_LGD_Maximum=("Stressed_LGD", "max"),
        )
        .reset_index()
    )

    numeric_summary_columns = [
        "Base_LGD_Mean", "Base_LGD_Minimum", "Base_LGD_Maximum",
        "Stressed_LGD_Mean", "Stressed_LGD_Minimum", "Stressed_LGD_Maximum"
    ]
    lgd_scenario_summary[numeric_summary_columns] = (
        lgd_scenario_summary[numeric_summary_columns].round(4)
    )

    expected_scenario_counts = {
        "Baseline": 10000,
        "Mild_Stress": 10000,
        "Severe_Stress": 10000,
    }
    lgd_scenario_summary["Expected_Record_Count"] = (
        lgd_scenario_summary["Scenario_Name"].map(expected_scenario_counts)
    )
    lgd_scenario_summary["Status"] = np.where(
        lgd_scenario_summary["Record_Count"]
        == lgd_scenario_summary["Expected_Record_Count"],
        "PASS", "FAIL"
    )

    failed_scenario_summaries = lgd_scenario_summary.loc[
        lgd_scenario_summary["Status"] != "PASS"
    ]
    if not failed_scenario_summaries.empty:
        raise ValueError("Scenario-wise LGD summary validation failed.")

    output_record_count = len(lgd_scenario_summary)
    records_processed = input_record_count

    print("=" * 80)
    print("SCENARIO-WISE LGD SUMMARY")
    print("=" * 80)
    display(lgd_scenario_summary)
    print("Scenario-wise LGD Summary Status: PASS")

    logger.info("Scenario-wise LGD summary generated successfully.")
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    logger.exception("Block 6 failed while generating LGD summary.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 6 : GENERATE SCENARIO-WISE LGD SUMMARY
START TIME : 2026-10-13 15:26:53
================================================================================
================================================================================
SCENARIO-WISE LGD SUMMARY
================================================================================

,Scenario_Name,Record_Count,Base_LGD_Mean,Base_LGD_Minimum,Base_LGD_Maximum,Stressed_LGD_Mean,Stressed_LGD_Minimum,Stressed_LGD_Maximum,Expected_Record_Count,Status
0,Baseline,10000,0.4529,0.2,0.85,0.4529,0.20,0.850,10000,PASS
1,Mild_Stress,10000,0.4529,0.2,0.85,0.4982,0.22,0.935,10000,PASS
2,Severe_Stress,10000,0.4529,0.2,0.85,0.5564,0.25,1.000,10000,PASS

Scenario-wise LGD Summary Status: PASS
2026-10-13 15:26:53,840 | INFO | Scenario-wise LGD summary generated successfully.

INFO:07_LGD_Stress_Impact:Scenario-wise LGD summary generated successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 3
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:26:53
DURATION (SECONDS) : 0.05
================================================================================

In [8]:
# =============================================================================
# CELL 08 - BLOCK 7: FINAL VALIDATION AND RECONCILIATION
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_pd)
output_record_count = len(portfolio_lgd)
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 7 : FINAL VALIDATION AND RECONCILIATION")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    final_duplicate_keys = int(
        portfolio_lgd[["Loan_ID", "Scenario_ID"]].duplicated().sum()
    )
    final_missing_base_lgd = int(portfolio_lgd["Base_LGD"].isna().sum())
    final_missing_lgd_factor = int(portfolio_lgd["LGD_Factor"].isna().sum())
    final_missing_stressed_lgd = int(portfolio_lgd["Stressed_LGD"].isna().sum())
    final_missing_lgd_band = int(portfolio_lgd["LGD_Band"].isna().sum())
    lgd_band_total = int(lgd_band_distribution.loc["Total", "Total"])

    validation_results = pd.DataFrame({
        "Validation_Check": [
            "Input and Output Record Count",
            "Expected Output Record Count",
            "Duplicate Loan-Scenario Keys",
            "Missing Base LGD",
            "Missing LGD Factor",
            "Missing Stressed LGD",
            "Missing LGD Band",
            "Invalid Base LGD",
            "Invalid Stressed LGD",
            "Formula / Cap Validation Exceptions",
            "LGD Band Distribution Total",
        ],
        "Expected_Result": [
            input_record_count, 30000, 0, 0, 0, 0, 0, 0, 0, 0, 30000
        ],
        "Actual_Result": [
            output_record_count, output_record_count, final_duplicate_keys,
            final_missing_base_lgd, final_missing_lgd_factor,
            final_missing_stressed_lgd, final_missing_lgd_band,
            invalid_base_lgd, invalid_stressed_lgd,
            formula_validation_exceptions, lgd_band_total
        ],
    })
    validation_results["Status"] = np.where(
        validation_results["Expected_Result"].astype(str)
        == validation_results["Actual_Result"].astype(str),
        "PASS", "FAIL"
    )

    lgd_stress_summary = pd.DataFrame({
        "Metric": [
            "Input Records", "Output Records", "Input Columns", "Output Columns",
            "Mortgage Base LGD", "Auto Loan Base LGD", "SME Loan Base LGD",
            "Corporate Loan Base LGD", "Personal Loan Base LGD",
            "Credit Card Base LGD", "Other Base LGD",
            "Baseline LGD Factor", "Mild Stress LGD Factor",
            "Severe Stress LGD Factor", "Minimum Stressed LGD",
            "Maximum Stressed LGD", "LGD Records Capped at 100%",
            "Low LGD Band Records", "Medium LGD Band Records",
            "High LGD Band Records", "Processing Timestamp"
        ],
        "Result": [
            input_record_count, output_record_count, input_column_count,
            len(portfolio_lgd.columns), 0.20, 0.35, 0.40, 0.45, 0.60, 0.85,
            0.50, 1.00, 1.10, 1.25,
            float(portfolio_lgd["Stressed_LGD"].min()),
            float(portfolio_lgd["Stressed_LGD"].max()), capped_lgd_records,
            int((portfolio_lgd["LGD_Band"] == "Low LGD").sum()),
            int((portfolio_lgd["LGD_Band"] == "Medium LGD").sum()),
            int((portfolio_lgd["LGD_Band"] == "High LGD").sum()),
            datetime.now()
        ],
    })

    failed_validations = validation_results.loc[
        validation_results["Status"] != "PASS"
    ]
    if not failed_validations.empty:
        raise ValueError("One or more Module 07 validation checks failed.")

    records_processed = output_record_count

    print("=" * 80)
    print("FINAL LGD STRESS IMPACT VALIDATION")
    print("=" * 80)
    display(validation_results)
    print("\nLGD Stress Module Summary:")
    display(lgd_stress_summary)
    print("Overall Module 07 Validation Status: PASS")

    logger.info("All Module 07 validation checks passed.")
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    logger.exception("Block 7 failed during final validation.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 7 : FINAL VALIDATION AND RECONCILIATION
START TIME : 2026-10-13 15:28:40
================================================================================
================================================================================
FINAL LGD STRESS IMPACT VALIDATION
================================================================================

                       Validation_Check  Expected_Result  Actual_Result Status
0         Input and Output Record Count            30000          30000   PASS
1          Expected Output Record Count            30000          30000   PASS
2          Duplicate Loan-Scenario Keys                0              0   PASS
3                      Missing Base LGD                0              0   PASS
4                    Missing LGD Factor                0              0   PASS
5                  Missing Stressed LGD                0              0   PASS
6                      Missing LGD Band                0              0   PASS
7                      Invalid Base LGD                0              0   PASS
8                  Invalid Stressed LGD                0              0   PASS
9   Formula / Cap Validation Exceptions                0              0   PASS
10          LGD Band Distribution Total            30000          30000   PASS

LGD Stress Module Summary:

                        Metric                      Result
0                Input Records                       30000
1               Output Records                       30000
2                Input Columns                          34
3               Output Columns                          38
4            Mortgage Base LGD                         0.2
5           Auto Loan Base LGD                        0.35
6            SME Loan Base LGD                         0.4
7      Corporate Loan Base LGD                        0.45
8       Personal Loan Base LGD                         0.6
9         Credit Card Base LGD                        0.85
10              Other Base LGD                         0.5
11         Baseline LGD Factor                         1.0
12      Mild Stress LGD Factor                         1.1
13    Severe Stress LGD Factor                        1.25
14        Minimum Stressed LGD                         0.2
15        Maximum Stressed LGD                         1.0
16  LGD Records Capped at 100%                        1555
17        Low LGD Band Records                        7650
18     Medium LGD Band Records                       13451
19       High LGD Band Records                        8899
20        Processing Timestamp  2026-10-13 15:28:40.746382

Overall Module 07 Validation Status: PASS
2026-10-13 15:28:40,772 | INFO | All Module 07 validation checks passed.

INFO:07_LGD_Stress_Impact:All Module 07 validation checks passed.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:28:40
DURATION (SECONDS) : 0.049
================================================================================

In [9]:
# =============================================================================
# CELL 09 - BLOCK 8: SAVE OUTPUTS, VERIFY FILES, AND CLOSE MODULE
# =============================================================================

block_start_time = datetime.now()
block_status = "STARTED"
input_record_count = len(portfolio_lgd)
output_record_count = 0
records_processed = 0

print("=" * 80)
print("MODULE 07: LGD STRESS IMPACT")
print("BLOCK 8 : SAVE OUTPUTS AND VERIFY FILES")
print("START TIME :", block_start_time.strftime("%Y-%m-%d %H:%M:%S"))
print("=" * 80)

try:
    portfolio_lgd.to_csv(OUTPUT_FILE, index=False, date_format="%Y-%m-%d")
    lgd_stress_summary.to_csv(SUMMARY_FILE, index=False)
    validation_results.to_csv(VALIDATION_FILE, index=False)
    lgd_scenario_summary.to_csv(SCENARIO_SUMMARY_FILE, index=False)
    lgd_band_distribution.to_csv(BAND_DISTRIBUTION_FILE)
    base_lgd_distribution.to_csv(PRODUCT_DISTRIBUTION_FILE, index=False)
    portfolio_lgd.head(25).to_csv(SAMPLE_FILE, index=False, date_format="%Y-%m-%d")

    logger.info("LGD-stressed portfolio and validation evidence saved successfully.")

    expected_output_files = [
        OUTPUT_FILE, SUMMARY_FILE, VALIDATION_FILE, SCENARIO_SUMMARY_FILE,
        BAND_DISTRIBUTION_FILE, PRODUCT_DISTRIBUTION_FILE, SAMPLE_FILE, LOG_FILE
    ]
    output_verification = pd.DataFrame({
        "File_Name": [file_path.name for file_path in expected_output_files],
        "Exists": [file_path.exists() for file_path in expected_output_files],
        "Size_Bytes": [
            file_path.stat().st_size if file_path.exists() else 0
            for file_path in expected_output_files
        ],
        "Full_Path": [str(file_path) for file_path in expected_output_files],
    })

    if not output_verification["Exists"].all():
        raise FileNotFoundError("One or more Module 07 output files were not created.")

    saved_output = pd.read_csv(OUTPUT_FILE, low_memory=False)
    output_record_count = len(saved_output)
    if output_record_count != 30000:
        raise ValueError(
            "Saved LGD-stressed portfolio does not contain the expected 30,000 records."
        )

    records_processed = output_record_count
    block_status = "SUCCESS"
except Exception:
    block_status = "FAILED"
    logger.exception("Block 8 failed while saving or verifying outputs.")
    raise
finally:
    block_end_time = datetime.now()
    block_duration_seconds = round((block_end_time - block_start_time).total_seconds(), 3)
    print("=" * 80)
    print("BLOCK STATUS       :", block_status)
    print("INPUT RECORDS      :", input_record_count)
    print("OUTPUT RECORDS     :", output_record_count)
    print("RECORDS PROCESSED  :", records_processed)
    print("END TIME           :", block_end_time.strftime("%Y-%m-%d %H:%M:%S"))
    print("DURATION (SECONDS) :", block_duration_seconds)
    print("=" * 80)

module_end_timestamp = datetime.now()
module_duration_seconds = round(
    (module_end_timestamp - module_start_timestamp).total_seconds(), 3
)

print("=" * 80)
print("PYTHON V2 - MODULE 07 COMPLETED")
print("LGD STRESS IMPACT EXECUTED SUCCESSFULLY")
print("=" * 80)
print("Input Records:", input_record_count)
print("LGD-Stressed Records:", output_record_count)
print("LGD-Stressed Output:", OUTPUT_FILE)
print("Validation Summary:", SUMMARY_FILE)
print("Validation Evidence:", VALIDATION_FILE)
print("Scenario LGD Summary:", SCENARIO_SUMMARY_FILE)
print("LGD Band Distribution:", BAND_DISTRIBUTION_FILE)
print("Product LGD Distribution:", PRODUCT_DISTRIBUTION_FILE)
print("Output Sample:", SAMPLE_FILE)
print("Execution Log:", LOG_FILE)
print("\nOutput File Verification:")
display(output_verification)
print("=" * 80)
print("MODULE STATUS             : SUCCESS")
print("MODULE START              :", module_start_timestamp.strftime("%Y-%m-%d %H:%M:%S"))
print("MODULE END                :", module_end_timestamp.strftime("%Y-%m-%d %H:%M:%S"))
print("TOTAL DURATION (SECONDS)  :", module_duration_seconds)
print("TOTAL RECORDS PROCESSED   :", output_record_count)
print("=" * 80)
print("All Module 07 output files verified successfully.")

logger.info(
    "Module 07 completed successfully in %s seconds.",
    module_duration_seconds
)

================================================================================
MODULE 07: LGD STRESS IMPACT
BLOCK 8 : SAVE OUTPUTS AND VERIFY FILES
START TIME : 2026-10-13 15:30:25
================================================================================
2026-10-13 15:30:27,295 | INFO | LGD-stressed portfolio and validation evidence saved successfully.

INFO:07_LGD_Stress_Impact:LGD-stressed portfolio and validation evidence saved successfully.

================================================================================
BLOCK STATUS       : SUCCESS
INPUT RECORDS      : 30000
OUTPUT RECORDS     : 30000
RECORDS PROCESSED  : 30000
END TIME           : 2026-10-13 15:30:27
DURATION (SECONDS) : 1.691
================================================================================
================================================================================
PYTHON V2 - MODULE 07 COMPLETED
LGD STRESS IMPACT EXECUTED SUCCESSFULLY
================================================================================
Input Records: 30000
LGD-Stressed Records: 30000
LGD-Stressed Output: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/output/portfolio_lgd.csv
Validation Summary: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/07_lgd_stress_summary.csv
Validation Evidence: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/07_lgd_stress_validation.csv
Scenario LGD Summary: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/07_lgd_scenario_summary.csv
LGD Band Distribution: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/07_lgd_band_distribution.csv
Product LGD Distribution: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/07_lgd_product_distribution.csv
Output Sample: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/validation/07_lgd_stress_sample.csv
Execution Log: /content/drive/MyDrive/Banking_Stress_Testing_V2_Python/logs/07_LGD_Stress_Impact.log

Output File Verification:

,File_Name,Exists,Size_Bytes,Full_Path
0,portfolio_lgd.csv,True,7738307,/content/drive/MyDrive/Banking_Stress_Testing_...
1,07_lgd_stress_summary.csv,True,553,/content/drive/MyDrive/Banking_Stress_Testing_...
2,07_lgd_stress_validation.csv,True,441,/content/drive/MyDrive/Banking_Stress_Testing_...
3,07_lgd_scenario_summary.csv,True,348,/content/drive/MyDrive/Banking_Stress_Testing_...
4,07_lgd_band_distribution.csv,True,174,/content/drive/MyDrive/Banking_Stress_Testing_...
5,07_lgd_product_distribution.csv,True,161,/content/drive/MyDrive/Banking_Stress_Testing_...
6,07_lgd_stress_sample.csv,True,6931,/content/drive/MyDrive/Banking_Stress_Testing_...
7,07_LGD_Stress_Impact.log,True,708,/content/drive/MyDrive/Banking_Stress_Testing_...

================================================================================
MODULE STATUS             : SUCCESS
MODULE START              : 2026-10-13 15:17:36
MODULE END                : 2026-10-13 15:30:27
TOTAL DURATION (SECONDS)  : 771.154
TOTAL RECORDS PROCESSED   : 30000
================================================================================
All Module 07 output files verified successfully.
2026-10-13 15:30:27,532 | INFO | Module 07 completed successfully in 771.154 seconds.

INFO:07_LGD_Stress_Impact:Module 07 completed successfully in 771.154 seconds.